### ISSUE TITLE
Bekomme das Plugin nicht geladen.

### ISSUE THREAD

**Issue by joey2212** [bombadiltom/homebridge-rademacher-homepilot#10]
Homebridge auf QNAP, jedes andere Plugin lässt sich laden. Homepilot Plugin spuckt tausende Errors aus und lädt nicht. Ging bis V0.0.6 noch. Any Ideas? Gäbe es ne Möglichkeit V0.0.6 anstelle von 0.0.7 zu laden?

**Comment by bombadiltom** [comment]
npm install <package>@<version>
Welche Fehler kommen denn?
Mit freundlichen Grüßen,

Tom Lorenz

**Comment by joey2212** [comment]
Hey Tom, 

same as here: [https://github.com/bombadiltom/homebridge-rademacher-homepilot/issues/11](url)

Werde mal den Tipp in dem Thread verfolgen und schauen was sich machen lässt.

Lg Joey
