### ISSUE TITLE
awning shows closed instead of open

### ISSUE THREAD

**Issue by HarriPinter** [bombadiltom/homebridge-rademacher-homepilot#100]
Hi Tom,

blinds/shutters and awning are working ... 
but: an awning (="Markise" (German)) is closed with status 0% and a blind is open with status 0%.
Homebridge shows awnings wrong: it shows open when it's closed and vise versa.

Is there a way to distinguish between blinds and awnings?
Any help is highly appreciated :-)

<img width="446" alt="markise" src="https://user-images.githubusercontent.com/77747198/111338306-1e267880-8677-11eb-92bb-72d1347f404f.png">

**Comment by HarriPinter** [comment]
@bombadiltom, any news here? :-)

**Comment by bombadiltom** [comment]
no, no news, but I have the same problem at home, so maybe I will find a solution when I need the awning which will hopefully be soon ;-)

**Comment by Ahhpaddy** [comment]
@bombadiltom any news here? maybe possible to invert states for each device?

**Comment by bombadiltom** [comment]
sorry, not possible
