### ISSUE TITLE
Since Version 0.7.0 the  DuoFern Universal-Aktor 2-Kanal does not work correctly

### ISSUE THREAD

**Issue by eibi63** [bombadiltom/homebridge-rademacher-homepilot#101]
[homebridge.log-2.txt](https://github.com/bombadiltom/homebridge-rademacher-homepilot/files/6254600/homebridge.log-2.txt)
Hallo Tom,

Seit der Version 0.7.0. Läuft der Universal – Aktor zwei Kanal immer wieder nur sporadisch nach Neustart der Homepage. Nach einer Weile reagiert das Gerät nicht mehr auf die HomeKit Steuerung. Die Schalter gehen an und sofort wieder aus. Teilweise sprechen sie gar nicht mehr an.

**Comment by eibi63** [comment]
Im Log-File sind das die Geräte 12 und 13.
Nach einem Downgrade auf 0.6.10 geht der Aktor.

**Comment by bombadiltom** [comment]
ich sehe da keine Fehler im Log, sieht nach irgendeiner Automation aus, die das schaltet

**Comment by eibi63** [comment]
Okay vielen Dank. Dann werde ich die mal überprüfen

Viele Grüße

J. Eibner

**Comment by eibi63** [comment]
Ich habe nun alle Automationen entfernt. Auch dann lassen sich die beiden Schalter über kurz oder lang nicht mehr bedienen.

**Comment by BaaZinga23** [comment]
Hallo, Ich habe das selbe Problem. Der Workaround mit Downgrade auf 6.9 dann läuft es wieder. 
Nochmals die Fehlerbeschreibung mit meinen Worten: 2-Kanal-Aktoren nehmen den Schaltbefehl scheinbar kurz an nach 10-15Sekunden wird der Schaltzustand wieder aktualisiert und man sieht das die Schalthandlung nicht ausgelöst wurde.

**Comment by eibi63** [comment]
Hallo Tom,

Auch nach dem Update von Rademacher besteht das Problem weiter. Nach dem Neustart der Bridge funktionieren die beiden Schalter. Nach kurzer Zeit reagieren sie aber nicht mehr. Eine Automation schaltet in diesem Fall nichts. Wie oben beschrieben, habe ich bereits alle Automation entfernt, trotzdem tritt das Problem auf. Wie gesagt, Nach einem downgrade auf 6.10. funktioniert es.

**Comment by bombadiltom** [comment]
1. stehen da sensible Passwörter im Log
2. hat das Plugin FritzPlatform das gleiche Problem

ggf. NodeJS updaten? 
was liefert denn z.B. "curl http://192.168.178.26/v4/devices/11", wenn das Plugin ausgestiegen ist?

**Comment by eibi63** [comment]
Hallo Tom,

1. Danke für den Hinweis
2. Das Plugin FritzPlattform hat kein Problem
3. 
{"response":"get_device","device":{"description":"Beleuchtung im Garten","deviceGroup":1,"did":11,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset5"},"messages":[],"name":"Gartenlicht","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"35001164","uid":"464801_1","voiceControlledBy":"","origin":"HomePilot","sceneConfig":["DIRECT_FUNCTION_CMD","TURN_ON_CMD","TURN_OFF_CMD","AUTO_MODE_CFG"]}}

**Comment by bombadiltom** [comment]
das ist doch der gleiche Fehler:
[06/06/2021, 01:38:37] [FritzPlatform] Error: No or invalid response: https://+++++:******%2F****@192.168.178.1:49443/upnp/control/x_tam - connect EHOSTUNREACH 192.168.178.1:49443 (EHOSTUNREACH)

**Comment by BitSJ9** [comment]
Hi, 

habe das gleiche Problem, sobald ich die Aktoren mit dem Homepilot geschaltet habe funktionieren die Aktoren wieder über HomeKit

**Comment by eibi63** [comment]
Hallo Tom,

Ich habe nun Node und NPM aktualisiert, HomePilot auf 8.0.1, aber der Bug besteht weiter. Nach dem Neustart der Bridge funktionieren die beiden Schalter. Nach kurzer Zeit reagieren sie aber nicht mehr oder sie gehen an und sofort wieder aus. Weder in der Bridge noch bei Homekit.  Die Autoren schalten einen Timer. Da kann man im Log schön sehen was passiert. Aktor geschaltet -> Timer an -> Timer aus. Eine andere Automation schaltet in diesem Fall nichts. Ein Neustart der Bridge oder eine Bedienung über den Home Pilot behebt das ganze für kurze Zeit. Bis zu Version 6.10. tritt das Problem nicht auf. 
[homebridge.log-4.txt](https://github.com/bombadiltom/homebridge-rademacher-homepilot/files/6757948/homebridge.log-4.txt)

**Comment by bombadiltom** [comment]
nochmal: das ist ein Problem der Umgebung, nicht des Plugins

[24/06/2021, 21:18:09] [FritzPlatform] An error occurred during polling hosts!
[24/06/2021, 21:18:09] [FritzPlatform] Error: connect EHOSTUNREACH 192.168.178.1:49443
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:89:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:213:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Fritzbox.getAllHostsV2 (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:199:22)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/presence/presence.handler.js:230:20) {
  title: 'No Response',
  code: 'EHOSTUNREACH',
  url: 'https://XXXXXXXX:'XXXXXXXX@192.168.178.1:49443/upnp/control/hosts'
}

**Comment by eibi63** [comment]
Das Plugin läuft alleine auf eine Unterbridge.

**Comment by eibi63** [comment]
Sorry, aber das ist kein Problem der Umgebung. Ich habe das Plugin auf eine ganz eigene Homebridge gesetzt ohne weitere Instanzen und ohne Automationen. Nach einer Weile lässt sich der Actor nicht mehr schalten, weder von HomeKit noch von der Bridge. Und noch mal: Bis zur Version 6.10. funktioniert es

**Comment by BitSJ9** [comment]
Ich habe jetzt auch noch etwas probiert und das Problem tritt immer beim Mehrfachwandtaster auf. Bei den anderen Geräten sporadisch und nicht regelmäßig.
Nach Neustart der Homebridge oder nach Bedienung über den Homepilot ist der Aktor wieder schaltbar über die Home App

**Comment by eibi63** [comment]
Die Fehler mit 'connect EHOSTUNREACH' sind behoben und treten nicht mehr auf. Das war ein Verbindungsproblem mit der Fritz!Box.
