### ISSUE TITLE
Blinds direct change of direction

### ISSUE THREAD

**Issue by Krillle** [bombadiltom/homebridge-rademacher-homepilot#102]
If the blinds button is tapped in Home App while the blinds are moving, the blinds change the direction immediately. This might kill the electric drive on the long term. 

Would be great if the plugin could determine if the blinds are in motion, and in that case send a stop signal first, before making them move to opposite direction.

**Comment by bombadiltom** [comment]
the plugin behaves exactly as the homepilot web application (send a PUT with GOTO_POS_CMD), so there is no need to change anything
