### ISSUE TITLE
RadermacherHomePilot Issue after upgrade to Hoobs 4

### ISSUE THREAD

**Issue by keschenbrenn** [bombadiltom/homebridge-rademacher-homepilot#103]
It seems that the plugin doesn't work anymore. RadermacherHomePliot latest version installed (0.8.1). 
Something failed with the migration to Hoobs version 4..

**Comment by bombadiltom** [comment]
please provide logs

**Comment by keschenbrenn** [comment]
Are you looking for these logs?

13:48:28WARNUNGunhandled rejection: Cancel
13:48:29HOOBS starting
13:48:40HOOBSLoaded plugin 'homebridge-rademacher-homepilot'
13:48:40HOOBSLoaded plugin 'homebridge-eufy-robovac'
13:48:40HOOBSFailed to find plugin to handle accessory Rolladen abc
13:48:40HOOBSFailed to find plugin to handle accessory Rolladen def
13:48:40HOOBSFailed to find plugin to handle accessory Rolloden ghi
13:48:40HOOBSFailed to find plugin to handle accessory Rolladen jkl
13:48:40HOOBSFailed to find plugin to handle accessory Rolladen mno
13:48:40HOOBSFailed to find plugin to handle accessory Rolladen pqr
13:48:40HOOBSFailed to find plugin to handle accessory Rolladen stu
13:48:40HOOBSFailed to find plugin to handle accessory Rolladen vwx
13:48:40HOOBSBridge is running on port 51826.
14:01:35Rademacher Homepilot Bridge starting
14:01:41Rademacher Homepilot BridgeWARNUNGNo plugins installed.
14:01:42Rademacher Homepilot BridgeBridge is running on port 52826.
14:01:50Rademacher Homepilot BridgeConfiguration change
14:01:50rademacherhomepilotbridge stopping
14:01:54Rademacher Homepilot Bridge starting
14:01:57Rademacher Homepilot BridgeLoaded plugin 'homebridge-rademacher-homepilot'
14:01:57Rademacher Homepilot BridgeLoading 1 platforms...
14:01:57Rademacher Homepilot BridgeRademacherHomePilotWarning. No password has been configured. Consider protecting access to your HomePilot.
14:01:57Rademacher Homepilot BridgeBridge is running on port 52826.
14:01:57Rademacher Homepilot BridgeRademacherHomePilotGET error for path undefined/v4/devices?devtype=Actuator: Error: Request failed with status code 400
    at createError (/var/lib/hoobs/rademacherhomepilotbridge/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/lib/hoobs/rademacherhomepilotbridge/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/lib/hoobs/rademacherhomepilotbridge/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:387:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
14:01:57Rademacher Homepilot BridgeRademacherHomePilotRequest failed: Error: Request failed with status code 400
14:01:57Rademacher Homepilot BridgeRademacherHomePilotGET error for path undefined/v4/devices?devtype=Sensor: Error: Request failed with status code 400
    at createError (/var/lib/hoobs/rademacherhomepilotbridge/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/lib/hoobs/rademacherhomepilotbridge/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/lib/hoobs/rademacherhomepilotbridge/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:387:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
14:01:57Rademacher Homepilot BridgeRademacherHomePilotRequest failed: Error: Request failed with status code 400
14:07:22Rademacher Homepilot BridgeConfiguration change
14:07:22rademacherhomepilotbridge stopping
14:07:24rademacherhomepilotbridge stopping
14:43:12WARNUNGdevice reboot command received
14:43:12HOOBS stopping
14:43:35hub is running on port 80
14:43:36HOOBS starting
14:43:39HOOBSLoaded plugin 'homebridge-eufy-robovac'
14:43:39HOOBSLoaded plugin 'homebridge-rademacher-homepilot'
14:43:39HOOBSBridge is running on port 51826.

**Comment by bombadiltom** [comment]
path undefined/v4/devices?d... => url is not configured, maybe whole configuration got lost?

**Comment by keschenbrenn** [comment]
So, what can I do?
In Hoobs version 4 a search for Rademacher doesn't show any result?
I don't want to de-install the plugin and then I can't install it again.

**Comment by bombadiltom** [comment]
ask hoobs support, I never used it

**Comment by keschenbrenn** [comment]
Hoobs support already contacted.

**Comment by keschenbrenn** [comment]
IP-address was the issue.
