### ISSUE TITLE
Sonnen/Windsensor Neu von Rademacher

### ISSUE THREAD

**Issue by ch4rly65** [bombadiltom/homebridge-rademacher-homepilot#104]
Hallo Tom,
Rademacher hat einen neuen Wind/Sonnensensor rausgebracht. Den habe ich mir auch zugelegt.
Er wird im Plugin wie folgt angezeigt:
name: 'DuoFern Sonne-/Windsensor',
  statusValid: true,
  deviceNumber: '32004464',
  uid: 'a90071_1',
  visible: true
Ist es Dir möglich diesen als neue sensoren anzeigen zu lassen?
Das wäre super.

VG Ch4Rly[

https://www.rademacher.de/shop/rollladen-sonnenschutz/sensoren/duofern-sonnen-windsensor-9499](url)

**Comment by bombadiltom** [comment]
add with
https://github.com/bombadiltom/homebridge-rademacher-homepilot/commit/088e3f225439033e92425a7c5d0169c870710f7c
(used wrong umber in comment)

**Comment by Charly-Man** [comment]
Hallo bekomme folgende Meldung im Plugin:

[8/2/2021, 12:51:50 PM] [RademacherHomePilot] Unknown product: 32004464
[8/2/2021, 12:51:50 PM] [RademacherHomePilot] {
  description: 'Markisenwächter',
  deviceGroup: 3,
  did: 1010018,
  automations: [ 30, 50 ],
  readings: { sun_detected: false, wind_detected: false },
  timestamp: 1627899537,
  iconSetInverted: 0,
  iconSet: { k: 'iconset25' },
  name: 'DuoFern Sonne-/Windsensor',
  statusValid: true,
  deviceNumber: '32004464',
  uid: 'a90071_1',
  visible: true

Gerät wird nicht angezeigt. 

Viele Grüße Ch4rly

**Comment by Charly-Man** [comment]
für die Version: homebridge-rademacher-homepilot v0.8.2
