### ISSUE TITLE
(Alte, gelöschte) Szenen von Homepilot weiterhin in Homebridge und HomeKit

### ISSUE THREAD

**Issue by iceweasel1** [bombadiltom/homebridge-rademacher-homepilot#105]
Ich habe vor ein paar Tage Homebridge aufgesetzt. Unter anderem auch dieses Plugin installiert. Die DuoFern-Gurtwickler wurden vom Plugin sofort erkannt und funktionieren bestens in HomeKit. Besten Dank hierfür!

Das Plugin hat ebenso zwei Szenen, die ich noch im Homepilot hatte, übernommen. Soweit so gut. Ich habe die Szenen im Homepilot nun vollständig entfernt. Leider bleiben diese im Plugin weiterhin bestehen und somit auch in HomeKit. Ein Entfernen der Szenen in Homebridge manuell, ist auch nicht möglich. 

Neustarts von Homebridge und dem Rademacher Homepilot bringen bislang ebenso keinen Erfolg. Das Plugin hier deaktivieren und wieder aktivieren, ebenso kein Erfolg. Die zwei bereits im Homepilot gelöschten Szenen bleiben konstant hier im Plugin. 

Gibt es hier eine Abhilfe?

**Comment by bombadiltom** [comment]
service homebridge stop
rm -f /etc/homebridge/accessories/cachedAccessories
service homebridge start
könnte helfen, dann sind aber auch alle Raumzuordnungen weg,
geht aber leider nicht anders
