### ISSUE TITLE
Fehler bei installation des plugins

### ISSUE THREAD

**Issue by bicmac** [bombadiltom/homebridge-rademacher-homepilot#11]
Hi, 
ich bekomme bei der installlation des Plugins auf meinem Raspberry eine Fehlermeldung.

pi@raspberry1:/usr/local/lib/node_modules $ sudo npm install -g homebridge-rademacher-homepilot

> curve25519-n@1.4.0 install /usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/curve25519-n
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/11.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/curve25519-n/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/curve25519-n/.node-gyp'
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/curve25519-n
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-14T20_59_49_902Z-debug.log

Die letzten Zeilen des genannten logfiles sind:

266 verbose pkgid curve25519-n@1.4.0
2267 verbose cwd /home/pi
2268 verbose Linux 4.14.79-v7+
2269 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-rademacher-homepilot"
2270 verbose node v11.6.0
2271 verbose npm  v6.5.0-next.0
2272 error code ELIFECYCLE
2273 error errno 1
2274 error curve25519-n@1.4.0 install: `node-gyp rebuild`
2274 error Exit status 1
2275 error Failed at the curve25519-n@1.4.0 install script.
2275 error This is probably not a problem with npm. There is likely additional logging output above.
2276 verbose exit [ 1, true ]

Danke für die Hilfe...

**Comment by jortgies** [comment]
Hi,
das ist kein Problem mit dem Plugin, sondern liegt an der verwendung von npm mit sudo.
Als quick fix könntest du versuchen das ganze mit
`sudo npm install -g homebridge-rademacher-homepilot --unsafe-perm`
neu zu installieren, oder der [npmjs.org Doku](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) folgen.
