### ISSUE TITLE
Manual button press in Rolltron DuoFern does not toogle automation in HomeKit 

### ISSUE THREAD

**Issue by Bassi44** [bombadiltom/homebridge-rademacher-homepilot#115]
Hi,
I‘ve tried to set an device status with HomeKit Automations when my Rolltron DuoFern is opened.
The automation works when I open the DuoFern within the HomeKit app. But it doesn’t work when I physically press the open button on my DuoFern. Status change of the DuoFern device is recognized in HomeKit, but no automation has been executed.

thanks for your help.

cheers

**Comment by bombadiltom** [comment]
tried it and it worked for me, do you have an Apple TV/iPad/... as a Home Hub?

**Comment by Bassi44** [comment]
You are right… it works. Turned out that there is sometimes a delay of the switched status shown in HomeKit.
