### ISSUE TITLE
Schwierigkeiten bei Installieren des Plug-Ins

### ISSUE THREAD

**Issue by Jens2022** [bombadiltom/homebridge-rademacher-homepilot#116]
Hallo, 

auch von mir zunächst mal vielen herzlichen Dank für das Plug-In. Es ist eines meiner LieblingsplugIns, weil es an sich total zuverlässig funktioniert. 

Ich musste heute meine Hoobs flahen weil sie nicht meh erreichbar war. Das Back-Up war noch von Version 3, klar habe ich jetzt 4 und natürlich gab es kein Back-Up. Also, noch mal von vorn (Anfängerfehler). 

Leider konnte ich das Rademacher Homepilot Plug In nicht erfolgreich installieren. Zunächst ging es über die MacOS app, aber nach dem Einbinden in das HomeKit. konnte ich die Rollos nicht sehen. 

Dann habe ich das Plug-In und die Bridge wieder gelöscht und habe den Prozess über die Homemanager App wieder gestartet Dort lies sich das Plug-In gar nicht mehr installieren (Fehlermeldung mit Hinweis auf Fehler beim Download). Dann habe ich es via Termin versucht. Dort habe ich folgende Fehlermeldung erhalten: 

hoobs@hoobs:~$ npm install -g homebridge-rademacher-homepilot
npm ERR! code EAI_AGAIN
npm ERR! syscall getaddrinfo
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/homebridge-rademacher-homepilot failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

Was habe ich falsch gemacht? 

Für einen Tipp wäre ich dankbar. 

MIt vielen Grüßen 

Jens

**Comment by bombadiltom** [comment]
das sind Netzwerkprobleme des Hoobs, das hat mit dem Plugin nichts zu tun, da kann ich leider nicht helfen
