### ISSUE TITLE
Namen der Geräte falsch

### ISSUE THREAD

**Issue by princemaxwell** [bombadiltom/homebridge-rademacher-homepilot#119]
Hi,
nach der Installation werden die Geräte vom Homepilot geholt. Wie es aussieht, wird hier allerdings die Beschreibung der Geräte aus dem Homepilot als Name verwendet und nicht der Name, der dem Gerät im Homepilot gegeben wurde.

Beispiel Konfiguration im Homepilot:
Name: Büro Heizung
Beschreibung: Heizkörper

Das Gerät wird dann nur als Heizkörper in der Homebridge angezeigt.

**Comment by bombadiltom** [comment]
ja, das ist Absicht, wenn die Beschreibung leer ist, wird der Name genommen
