### ISSUE TITLE
Add-Z

### ISSUE THREAD

**Issue by cturpel** [bombadiltom/homebridge-rademacher-homepilot#120]
Hallo,

Ist es geplant den Add-Z Stick und die ZigBee Kompatiblen Leuchtmittel vom Homepilot zu integrieren?
Ich würde mich auch irgendwie an der Arbeit beteiligen, habe leider nur Rudimentäre programmierkenntnisse...

Danke,

**Comment by bombadiltom** [comment]
ich habe mal meine Hue-Leuchten als Dimmer hinzugefügt, leider kann man damit nur die Helligkeit einstellen, nicht aber die Farben
