### ISSUE TITLE
Homepilot -> Smartbox

### ISSUE THREAD

**Issue by diddi103** [bombadiltom/homebridge-rademacher-homepilot#126]
Hallo,

Rademacher hat neue, bzw. Produkte mit neuen ID Nummern versehen, da man diese nun unter dem Namen Smart vermarktet. 

Thermostate  haben nun die ID Nr. 13601000 sind aber baugleich mit den Duofern 9433-1

Rollladenaktor haben nun die ID Nr. 10502002 sind baugleich Duofern 5615-UW

Sonnensensoren haben nun die ID 10771003 sind baugleich Duofern 9478-1

Leider werden diese nicht von deinem Plugin nicht erkannt sondern nur als "unknown product"

Gibt es eine Möglichkeit, diese einzubinden.

VG
Diddi103

**Comment by bombadiltom** [comment]
ja, einfach hinzufügen wie hier zum Beispiel:
https://github.com/bombadiltom/homebridge-rademacher-homepilot/pull/125/commits/a2bee7dac5bfa94bcdde0771dd6669ce17f191ff

**Comment by diddi103** [comment]
kannst Du mir auch sagen in welchem Verzeichnis die Datei liegt

**Comment by bombadiltom** [comment]
https://github.com/bombadiltom/homebridge-rademacher-homepilot/blob/master/index.js

**Comment by bombadiltom** [comment]
in release 0.9.3 enthalten ;-)

**Comment by diddi103** [comment]
habe mich verschrieben bei den Thermostaten muss es heißen 13601001
die Sonnensensoren werden trotz 10771003 als unbekannt angezeigt

Vg
Dirk

**Comment by bombadiltom** [comment]
zum Sonnensensor bitte mal ein Log senden

**Comment by diddi103** [comment]
Wenn Du mir sagst welches Log Du genau haben möchtest, bzw. wie ich es anstelle dieses zu generiern.

Wenn Du das Standardlog von Hoobs meinst kein Thema

**Comment by bombadiltom** [comment]
Hoobs kenne ich nicht, irgendwo loggen die Plugins hin, sollte so aussehen:

[8/3/2023, 10:36:17 AM] [RademacherHomePilot] Unknown product: 99999980

**Comment by bombadiltom** [comment]
Sonnensensoren sollten jetzt gehen, die müssen an zwei Stellen eingefügt werden
