### ISSUE TITLE
Homepilot Rollotron pure smart (10122345) unknown product

### ISSUE THREAD

**Issue by ThomaldoS** [bombadiltom/homebridge-rademacher-homepilot#127]
Hallo bombadiltom,
Ich habe fünf Homepilot Rollotron pure Smart (10122345) und möchte diese über die Smarthome Box in meine Homebridge einbinden. Leider erscheinen diese bei mir als „Unknown product: 10122345“ im Log-File.
Können diese bitte in das Plugin integriert werden?
Vielen Dank!

**Comment by bombadiltom** [comment]
in 0.9.5 hinzugefügt

**Comment by ThomaldoS** [comment]
Wow, ich bin sehr beeindruckt für die schnelle Lösung, vielen lieben Dank!
