### ISSUE TITLE
Rollladenmotor premium smart s10

### ISSUE THREAD

**Issue by Ganner86** [bombadiltom/homebridge-rademacher-homepilot#129]
Hallo bombadiltom,
Ich habe einen Rollladenmotor premium smart s10 zuhause installiert, leider erscheint diese bei mir als „Unknown product: 10236020“ im Log-File.
Kannst du diese im Plugin einfügen oder mir eventuell sagen wie ich es selbst lösen kann?

Vielen Dank im voraus

**Comment by Ganner86** [comment]
Hab es hin bekommen.
Meine Programmierkenntnisse halten sich zwar sehr stark in Grenzen aber ich habe in der index.js in der function RademacherHomePilot unter den Devices //blinds gefunden. Darunter in dem Array scheint die Devicelist der Rollladenmotoren zu sein. Da diverse baugleiche Geräte bereits integriert sind habe ich dort die ID meines Typ eingetragen. 
Hat bei mir funktioniert falls noch jemand das Problem haben sollte.

**Comment by bombadiltom** [comment]
genau so geht's ;-)
