### ISSUE TITLE
Plugin zeigt nicht alle Werte des Umweltsensors

### ISSUE THREAD

**Issue by trichte** [bombadiltom/homebridge-rademacher-homepilot#13]
Danke für die Integration des Umweltsensors. Es werden aber noch nicht alle Werte gezeigt.
Bisher wird nur das Signal für die Temperatur und die Lichtstärke angezeigt.
Das Signal für Regen sowie die Windstärke fehlen.

**Comment by bombadiltom** [comment]
see #5 : "Homebridge supports only temperature and light."

**Comment by sg70** [comment]
@trichte ich habe ein wenig mit HomeKit herumgespielt sofern eigene Signale definiert werden, kann HomeKit sie nicht mehr anzeigen. Eine andere Option wäre die Nutzung von anderen vordefinierten Sensoren (https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js).
