### ISSUE TITLE
Login geht nur ohne Passwort

### ISSUE THREAD

**Issue by macintosh68** [bombadiltom/homebridge-rademacher-homepilot#130]
Hallo
2 Probleme hab ich:

Login geht nur ohne Passwort, mit Passwort gehasted oder Klartext komm ich nicht rein

Ohne Passwort klappt scheinbar der Login aber er bekommt keine Geräte Infos:

[0;36mLoading logs using native method...
[0m[0;36mFile: /var/lib/homebridge/homebridge.log

[37m[06/10/2023, 09:32:17] [39mRegistering platform 'homebridge-rademacher-homepilot.RademacherHomePilot'

[37m[06/10/2023, 09:32:17] [39m[36m[RademacherHomePilot][39m Loaded homebridge-rademacher-homepilot v0.10.4 child bridge successfully

[37m[06/10/2023, 09:32:17] [39mLoaded 0 cached accessories from cachedAccessories.96C4F9C79AD7.

[37m[06/10/2023, 09:32:17] [39m[36m[RademacherHomePilot][39m Debugging...

[37m[06/10/2023, 09:32:17] [39m[36m[RademacherHomePilot][39m Warning. No password has been configured. Consider protecting access to your HomePilot.

[37m[06/10/2023, 09:32:18] [39mHomebridge v1.6.1 (HAP v0.11.1) (RademacherHomePilot) is running on port 35039.

[37m[06/10/2023, 09:32:18] [39m[36m[RademacherHomePilot][39m GET error for path 192.168.178.61/v4/devices?devtype=Actuator: [AxiosError: Request failed with status code 400] {

  code: 'ERR_BAD_REQUEST',

  config: [Object],

  request: [ClientRequest],

  response: [Object]

}

[37m[06/10/2023, 09:32:18] [39m[36m[RademacherHomePilot][39m Request failed: AxiosError: Request failed with status code 400

[37m[06/10/2023, 09:32:18] [39m[36m[Max EQ3][39m Connected to Max! Cube.

[37m[06/10/2023, 09:32:18] [39m[36m[RademacherHomePilot][39m GET error for path 192.168.178.61/v4/devices?devtype=Sensor: [AxiosError: Request failed with status code 400] {

  code: 'ERR_BAD_REQUEST',

  config: [Object],

  request: [ClientRequest],

  response: [Object]

}

[37m[06/10/2023, 09:32:18] [39m[36m[RademacherHomePilot][39m Request failed: AxiosError: Request failed with status code 400

[37m[06/10/2023, 09:32:18] [39m[36m[RademacherHomePilot][39m GET error for path 192.168.178.61/v4/scenes: [AxiosError: Request failed with status code 400] {

  code: 'ERR_BAD_REQUEST',

  config: [Object],

  request: [ClientRequest],

  response: [Object]

}

[37m[06/10/2023, 09:32:18] [39m[36m[RademacherHomePilot][39m Request failed: AxiosError: Request failed with status code 400

**Comment by Cabriojoschy** [comment]
Wenn du das neue Homepilot Gateway Premium hast, wird das wahrscheinlich nicht funktionieren. Ich habe heute wegen dem gleichen Fehler den Support kontaktiert. Das neue Gateway hat keine Weboberfläche mehr, ist deswegen auch im lokalen Netzwerk nicht erreichbar (bzw. es kommt eine 404 Seite) es ist auf reine App Nutzung ausgelegt. 
@bombadiltom: siehst du irgendwelche Chancen das neue Gateway zum laufen zu bringen? Oder wie muss man das Plugin konfigurieren? weil auch bei mir sowohl mit Passwort als auch ohne nur Fehlermeldungen kommen.

**Comment by bombadiltom** [comment]
wenn es keine Weboberfläche gibt, wie setzt man dann ein Passwort?

da 404 und 400 geliefert wird, scheint immerhin ein Webserver vorhanden zu sein.

ich denke, da hilft nur ein Mitschneiden der Kommunikation zwischen App und Gateway, denke nicht, dass das alles über das Internet läuft.

Und wieso heißt das Gerät Premium, wenn es weniger kann?

**Comment by bombadiltom** [comment]
zum usorünglichen Fehler:

"GET error for path 192.168.178.61/v4/devices?devtype=Actuator"

->

die url ist falsch, muss http://192.168.177.61 sein und nicht nur die IP

**Comment by Cabriojoschy** [comment]
> wenn es keine Weboberfläche gibt, wie setzt man dann ein Passwort?
> 
> da 404 und 400 geliefert wird, scheint immerhin ein Webserver vorhanden zu sein.
> 
> ich denke, da hilft nur ein Mitschneiden der Kommunikation zwischen App und Gateway, denke nicht, dass das alles über das Internet läuft.
> 
> Und wieso heißt das Gerät Premium, wenn es weniger kann?

Du musst in der App einen Nutzer anlegen inkl. Passwort, für den Fernzugriff. 
Ich bin mir nicht sicher, warum solch ein Schritt erfolgt, bin auf jeden Fall bedient und kurz davor das Gateway gegen ein älteres zu tauschen. 
die dauerhafte Nutzung der nativen App ist jedenfalls keine Option…

**Comment by luxx-fr** [comment]
Habe auch alles mögliche probiert. Es gibt ein Home Assistant Plugin, welches mit dem neuen Gateway (Homepilot Gateway Premium) funktioniert - https://github.com/peribeir/homeassistant-rademacher . Dieses habe ich dann an HomeKit weitergereicht. Nichtsdestotrotz wäre es natürlich einfacher ein Homebridge Plugin zu haben! Würde ein "natives" Homebridge Plugin feiern!

**Comment by bombadiltom** [comment]
danach https://github.com/peribeir/homeassistant-rademacher/commit/31d73e0986d64db5d441295acceeffc8e6030626
müsste es genügen, wenn du "/hp" an die URL anhängst, also statt "http://homepilot" -> "http://homepilot/hp"

**Comment by luxx-fr** [comment]
> danach [peribeir/homeassistant-rademacher@31d73e0](https://github.com/peribeir/homeassistant-rademacher/commit/31d73e0986d64db5d441295acceeffc8e6030626) müsste es genügen, wenn du "/hp" an die URL anhängst, also statt "http://homepilot" -> "http://homepilot/hp"

Top, danke für die schnelle Antwort!

Die Verbindung kann nun aufgebaut werden. Szenen werden allerdings nicht gefunden und der Gurtwickler wird als "unkown product" gefunden.

[RademacherHomePilot] Unknown product: 10251530

**Comment by luxx-fr** [comment]
> Ist "Scenes as switch" angeschaltet?

Hatte es ursprünglich eingeschaltet. Daraufhin gab es allerdings Fehlermeldungen, sodass ich "Scenes as switch" deaktiviert habe.

[RademacherHomePilot] Unknown product: 10251530  <- diese Meldung gab es weiterhin und der Gurtwickler erscheint nicht in HomeKit

**Comment by bombadiltom** [comment]
Gurtabwickler in https://github.com/bombadiltom/homebridge-rademacher-homepilot/releases/tag/0.10.7

**Comment by bombadiltom** [comment]
Ohne "Scenes as switch" keine Szenen, welche Fehlermeldungen denn?

**Comment by luxx-fr** [comment]
> Gurtabwickler in https://github.com/bombadiltom/homebridge-rademacher-homepilot/releases/tag/0.10.7

Vielen Dank für das Update! Der Gurtwickler wird nun erkannt.

**Comment by luxx-fr** [comment]
> Ohne "Scenes as switch" keine Szenen, welche Fehlermeldungen denn?

Wenn ich "Scenes as switch" auf "true" setze sieht der Log wie folgt aus:

[27.11.2023, 15:25:53] [RademacherHomePilot] GET error for path http://192.168.1.44/hp/v4/scenes: [AxiosError: Request failed with status code 501] {
  code: 'ERR_BAD_RESPONSE',
  config: [Object],
  request: [ClientRequest],
  response: [Object]
}
[27.11.2023, 15:25:53] [RademacherHomePilot] Request failed: AxiosError: Request failed with status code 501
[27.11.2023, 15:25:53] [RademacherHomePilot] blinds are online: Deine Gerätebeschreibung [2]

**Comment by luxx-fr** [comment]
> > Ohne "Scenes as switch" keine Szenen, welche Fehlermeldungen denn?
> 
> Wenn ich "Scenes as switch" auf "true" setze sieht der Log wie folgt aus:
> 
> [27.11.2023, 15:25:53] [RademacherHomePilot] GET error for path http://192.168.1.44/hp/v4/scenes: [AxiosError: Request failed with status code 501] { code: 'ERR_BAD_RESPONSE', config: [Object], request: [ClientRequest], response: [Object] } [27.11.2023, 15:25:53] [RademacherHomePilot] Request failed: AxiosError: Request failed with status code 501 [27.11.2023, 15:25:53] [RademacherHomePilot] blinds are online: Deine Gerätebeschreibung [2]

Wenn "Scenes as switch" auf "false" gesetzt ist, erhalte ich im Log keine Fehlermeldung

**Comment by luxx-fr** [comment]
> > Ohne "Scenes as switch" keine Szenen, welche Fehlermeldungen denn?
> 
> Wenn ich "Scenes as switch" auf "true" setze sieht der Log wie folgt aus:
> 
> [27.11.2023, 15:25:53] [RademacherHomePilot] GET error for path http://192.168.1.44/hp/v4/scenes: [AxiosError: Request failed with status code 501] { code: 'ERR_BAD_RESPONSE', config: [Object], request: [ClientRequest], response: [Object] } [27.11.2023, 15:25:53] [RademacherHomePilot] Request failed: AxiosError: Request failed with status code 501 [27.11.2023, 15:25:53] [RademacherHomePilot] blinds are online: Deine Gerätebeschreibung [2]

Ich habe allerdings im HomePilot bislang auch noch keine Szene erstellt, könnte es sonst auch daran liegen?

**Comment by bombadiltom** [comment]
> Wenn ich "Scenes as switch" auf "true" setze sieht der Log wie folgt aus:
> 
> [27.11.2023, 15:25:53] [RademacherHomePilot] GET error for path http://192.168.1.44/hp/v4/scenes: [AxiosError: Request failed with status code 501] { code: 'ERR_BAD_RESPONSE', config: [Object], request: [ClientRequest], response: [Object] } [27.11.2023, 15:25:53] [RademacherHomePilot] Request failed: AxiosError: Request failed with status code 501 [27.11.2023, 15:25:53] [RademacherHomePilot] blinds are online: Deine Gerätebeschreibung [2]

501 heißt "Not implemented"... kann das Ding überhaupt Szenen? Vielleicht mal ausprobieren ;-)

**Comment by luxx-fr** [comment]
Es gibt dort nur "Routinen" - aber Szenen habe ich keine gefunden. Könnte also daran liegen ;)

Woher holt das Plugin den Namen des Gurtwicklers? - Aktuell heißt dieser "Deine Gerätebeschreibung". Ich weiß ich kann es in HomeKit umbenennen, daher nur aus Interesse.

Und was mir aufgefallen ist: Dein HomeBridge Plugin funktioniert auch mit aktiviertem Passwortschutz auf der HomePilot Bridge im Gegensatz zu dem Home Assistant Plugin (zumindest gemäß der Dokumentation).

**Comment by bombadiltom** [comment]
Der Name kommt aus der Beschreibung, wenn diese gefüllt ist, ansonsten aus dem Namen selbst, hatte ich mal so eingebaut, damit man in Beschreibung den Homekit-Namen anders vergeben kann als im Homepilot

**Comment by luxx-fr** [comment]
> Der Name kommt aus der Beschreibung, wenn diese gefüllt ist, ansonsten aus dem Namen selbst, hatte ich mal so eingebaut, damit man in Beschreibung den Homekit-Namen anders vergeben kann als im Homepilot

Alles klar. Als Rückmeldung: Beim HomePilot Premium Gateway hat er nur die Beschreibung genommen, obwohl diese bei mir leer war und hat dann nicht den Namen genommen. - Habe den Rolladen dann in HomeKit korrekt benannt, von daher passt bei mir nun alles.

Vielen vielen Dank für die schnellen Rückmeldungen! Ist es top! Danke!
