### ISSUE TITLE
Duo Fern Heizkörperstellantrieb

### ISSUE THREAD

**Issue by Ghost1299** [bombadiltom/homebridge-rademacher-homepilot#131]
Der Stellantrieb hat keinen feuchtigkeitssensor, trotzdem wird der in HomeKit angezeigt, kann man das irgendwie abstellen?

**Comment by Ghost1299** [comment]
Ebenso werden auch die Optionen Kühlung und automatisch angezeigt die es auch nicht gibt, bekommt man die auch ausgeblendet?

**Comment by bombadiltom** [comment]
Letzteres geht, Feuchtigkeitssensor kann ich nur den Wert ändern, habe mal 50% fix gesetzt...
