### ISSUE TITLE
"No Answer" in Home

### ISSUE THREAD

**Issue by boesermichl** [bombadiltom/homebridge-rademacher-homepilot#133]
Since Update, in Hoobs (Homebridge) shows every device, can be driven, but in Home-App all of them are telling "No Answer"

Home is driven by Homepod Mini

**Comment by bombadiltom** [comment]
if homebridge works fine, it is no problem of the plugin and I can't help here, try to restart Homepod and iPhone

**Comment by bombadiltom** [comment]
are there any errors visible in the homebridge log?

**Comment by xytras2305** [comment]
Same Problem here. @boesermichl did you find a solution? Is it working again?

**Comment by boesermichl** [comment]
I deleted the whole Plugin in hoobs and reinstalled it. This made it After restart of homebridge
