### ISSUE TITLE
Rademacher DuoFern Hutschienen Schaltaktor 2-​Kanal Typ 9470-​4 

### ISSUE THREAD

**Issue by eibi63** [bombadiltom/homebridge-rademacher-homepilot#135]
Nur eine kurze Frage: Wird der Rademacher DuoFern Hutschienen Schaltaktor 2-​Kanal Typ 9470-​4 vom Plugin unterstützt?

**Comment by bombadiltom** [comment]
ja, seit 0.9.6: https://github.com/jortgies/homebridge-rademacher-blinds/commit/646be195162139ea745ae4d49e11765e9645ce6a

https://service.rademacher.de/hc/article_attachments/11976371075858
