### ISSUE TITLE
Osram On/Off Zigbee Plug über AddZ einbinden?

### ISSUE THREAD

**Issue by stmwe** [bombadiltom/homebridge-rademacher-homepilot#138]
Hallo an Alle,

Ist es möglich über AddZ an Homepilat angebundenen On/Off Plugs z.B. Osram/Ledvance über das Plugin an Homebridge anzubinden.  Im Moment ist es unknown [RademacherHomePilot] Unknown product: 99999960.

Die Beschreibung über http://x.x.x.x/v4/devices ist wie folgt:	

> 21
> description	"Schreibtisch Strom"
> deviceGroup	1
> did	60
> hasErrors	0
> iconSetInverted	0
> iconSet	
> k	"iconset10"
> messages	[]
> name	"Office Desk"
> properties	
> closingContact	3
> dawn	3
> dusk	3
> motion	3
> rain	3
> smartphone	3
> smoke	3
> sun	3
> temperature	3
> time	3
> trigger	3
> warning	3
> wind	3
> statusValid	true
> statusesMap	
> Position	0
> visible	true
> deviceNumber	"99999960"
> uid	"ZIG_F0D1B80000153B4E"
> voiceControlledBy	"Alexa"
> origin	"HomePilot"
> 22
> 

Danke im Voraus,

Stefan

**Comment by bombadiltom** [comment]
should work in 0.10.9

**Comment by stmwe** [comment]
excellent, many thanks
