### ISSUE TITLE
2nd question for Osram On/Off Zigbee Plug über AddZ einbinden? #138

### ISSUE THREAD

**Issue by stmwe** [bombadiltom/homebridge-rademacher-homepilot#139]
Hi,

I installed V0.10.9 and now I can see the plugs in Hombridge, but they do not react on any commands.
The icon changes from on to off, but the switch command does not reach it and is not executed.

Any further information required / needed to be retrieved?

Regards,

Stefan

**Comment by bombadiltom** [comment]
anything in the logs?

**Comment by stmwe** [comment]
i see the device is getting detected by the plugin and it is visible nothing more,
its shown under accessories and the icon changes when switching on/off

**Comment by stmwe** [comment]
switching from Rademacher Smart home-box works and i can see also the status change 
 statusesMap:
          Position:	100
toggling between 0 or 100.
When switching from homebridge status doesn't change.

I also tried to delete / add the plugs in the Rademacher box but no effect.

**Comment by stmwe** [comment]
got it working, the plugs got new did while reconnecting which were not in the did filter, and the plugs shown under accessories were old cache entries, now its workingbfrom home bridge too.

Again many thanks,

Stefan
