### ISSUE TITLE
DouFern Funk-Heizkörperthermostat unterstützt?

### ISSUE THREAD

**Issue by joey2212** [bombadiltom/homebridge-rademacher-homepilot#14]
Hi Tom, nachdem nun alles läuft wollte ich mal nachfragen: mein Vater hat in seinem Homepilot Setup auch Funk Heizkörperthermostate laufen, welche er gerne auch in HomeKit nutzen würde. Kommt hierfür noch Unterstützung?

Beste Grüße
Joey

**Comment by bombadiltom** [comment]
Moin, hab leider keins, wollte mir aber irgendwann mal eins zulegen. Rademacher stellt leider keine Geräte...

**Comment by martak101** [comment]
Hallo zusammen,

habe hier ebenfalls Interesse.
Wenn es daran scheitert, dass bombadiltom ein Thermostat fehlt, bekommen wir da bestimmt was organisiert.

**Comment by bombadiltom** [comment]
https://www.paypal.me/tlorenz ;-)

**Comment by martak101** [comment]
@bombadiltom 
Danke für den Link.
Hoffe, es reicht ;-)
Wenn ich beim Test o.ä. unterstützen kann, gerne

**Comment by bombadiltom** [comment]
Wow, vielen Dank, Gerät ist bestellt.

**Comment by bombadiltom** [comment]
Erste funktionierende Version im branch feature/duofern9433

**Comment by bombadiltom** [comment]
supported with release 0.1.0

**Comment by carbonide** [comment]
Ich habe ein Update auf Version 0.1.0 gemacht, sehe aber immer nur noch die Rolläden.

Muss etwas an der config geändert werden um auch die Thermostaten einzubinden?

**Comment by bombadiltom** [comment]
Nein, was steht denn im Log?

**Comment by carbonide** [comment]
ier ist ein auszug aus dem Log:

`[4/21/2019, 9:22:49 AM] Homebridge is running on port 51826.
stdout
07:22:49
[4/21/2019, 9:22:49 AM] [SmallStation] do poll...
stdout
07:22:50
[4/21/2019, 9:22:50 AM] [RademacherHomePilot] Unknown product: Télécommande standard DuoFern (6 gr. - 48 appareils)
stdout
07:22:50
[4/21/2019, 9:22:50 AM] [RademacherHomePilot] blinds are online: Store Bureau [10000]
stdout
07:22:50
[4/21/2019, 9:22:50 AM] [RademacherHomePilot] blinds are online: Store Chambre [10002]
stdout
07:22:50
[4/21/2019, 9:22:50 AM] [RademacherHomePilot] Unknown product: Actionneur pour radiateur Z-Wave
stdout
07:22:51
[4/21/2019, 9:22:51 AM] [SmallStation] current power state is: true
stdout
07:22:51
[4/21/2019, 9:22:51 AM] [SmallStation] poll end, state: true
stdout
07:23:11
[4/21/2019, 9:23:11 AM] [homebridge-config-ui-x] Multiple Instances Of Homebridge Found Installed
stdout
07:23:11
[4/21/2019, 9:23:11 AM] [homebridge-config-ui-x] /homebridge/node_modules/homebridge
stdout
07:23:11
[4/21/2019, 9:23:11 AM] [homebridge-config-ui-x] /usr/local/lib/node_modules/homebridge
stdout
07:24:48
[4/21/2019, 9:24:48 AM] [RademacherHomePilot] Store Bureau - Setting target position: 50`

Kann es sein, dass es bei mir nicht funktioniert da ich meinen Homepilot auf französisch eingestellt habe: "Unknown product: Actionneur pour radiateur Z-Wave" <- das müsste nämlich das Thermostat sein.

**Comment by bombadiltom** [comment]
Ja, das ist das Problem, in der JSON stehen nur die Namen zur Unterscheidung der Gerätetypen.
Könnte man aber aufnehmen

**Comment by carbonide** [comment]
Ich wäre dir sehr dankbar dafür!

Benötigst du eine Übersetzung der verschiedenen Gerätetypen?

**Comment by bombadiltom** [comment]
Ja, am besten productName aus http://IP-Adresse des hompilot/deviceajax.do?devices=1

**Comment by bombadiltom** [comment]
Wahrscheinlich ginge es auch über die ersten zwei Ziffern der Seriennummer...

**Comment by carbonide** [comment]
Output von hompilot/deviceajax.do?devices=1:

`{ "response" : "get_visible_devices", "status" : "ok", "devices" : [{"did":10000,"name":"Store Bureau","description":"","initialized":1,"position":50,"productName":"RolloTron Standard DuoFern","serial":"40 5A 2E","statusesMap":{"Position":50,"Manuellbetrieb":100},"status_changed":1555831493,"deviceGroup":2,"iconSet":{"name":"Rollladen 1","description":"Rollladen Icon-Set","strMin":"Auf","strMax":"Zu","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/rollladen1.png", "numTiles" : 5 },"k":"iconset8"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"405A2E_1","visible":true,"groups" : [ 5001 ] ,"favoredId":5000,"properties":{"rain":3,"smartphone":3,"motion":3,"dusk":3,"smoke":3,"favored":0,"trigger":3,"manual":3,"sun":3,"generic":3,"closingContact":3,"temperature":3,"temperator":3,"warning":3,"dawn":3,"time":3,"dust":3,"wind":3,"states":[{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":0},{"cfgKey":"setSunAuto","cfgId":105,"state":0},{"cfgKey":"setMorningAuto","cfgId":103,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setEveningAuto","cfgId":107,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setAutomationOverall","cfgId":99,"state":1},{"cfgKey":"null","cfgId":0,"state":0}]},"sortId":0,"sTypes":[],"version":"1.0","sync":-2147481162,"messages":[],"hasErrors":0,"autos":[2,0,3,4,1]},{"did":10002,"name":"Store Chambre","description":"","initialized":1,"position":58,"productName":"RolloTron Standard DuoFern","serial":"40 66 B3","statusesMap":{"Position":58,"Manuellbetrieb":100},"status_changed":1555828502,"deviceGroup":2,"iconSet":{"name":"Rollladen 1","description":"Rollladen Icon-Set","strMin":"Auf","strMax":"Zu","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/rollladen1.png", "numTiles" : 5 },"k":"iconset8"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"4066B3_1","visible":true,"groups" : [ 5000 ] ,"favoredId":5004,"properties":{"rain":3,"smartphone":3,"motion":3,"dusk":3,"smoke":3,"favored":0,"trigger":3,"manual":3,"sun":3,"generic":3,"closingContact":3,"temperature":3,"temperator":3,"warning":3,"dawn":3,"time":3,"dust":3,"wind":3,"states":[{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":0},{"cfgKey":"setSunAuto","cfgId":105,"state":0},{"cfgKey":"setMorningAuto","cfgId":103,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setEveningAuto","cfgId":107,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setAutomationOverall","cfgId":99,"state":1},{"cfgKey":"null","cfgId":0,"state":0}]},"sortId":0,"sTypes":[],"version":"1.0","sync":-2147481198,"messages":[],"hasErrors":0,"autos":[2,0,3,4,1]},{"did":1010001,"name":"Thermo Bureau","description":"","initialized":1,"position":40,"productName":"Actionneur pour radiateur Z-Wave","serial":"3","statusesMap":{"Position":40,"Manuellbetrieb":0},"status_changed":1555834597,"deviceGroup":5,"iconSet":{"name":"Thermostat","description":"Thermostat Icon-Set","strMin":"An","strMax":"Aus","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/thermostat-set.png", "numTiles" : 5 },"k":"iconset28"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"ZW_2_5_3","visible":true,"groups" : [ 5001 ] ,"favoredId":5002,"properties":{"rain":3,"smartphone":3,"motion":3,"dusk":3,"smoke":3,"favored":0,"trigger":3,"manual":3,"sun":3,"generic":3,"closingContact":3,"temperature":3,"temperator":3,"warning":3,"dawn":3,"time":3,"dust":3,"wind":3,"states":[{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":1},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setClosingContactAuto","cfgId":118,"state":1},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"null","cfgId":0,"state":0}]},"sortId":0,"sTypes":[],"version":"1.0","sync":-2147471594,"messages":[],"hasErrors":0,"autos":[2,3,11],"posMin":40,"posMax":280}] }`

**Comment by carbonide** [comment]
An einem anderem Ort habe ich noch einen Homepilot mit Umweltsensor und Zwwischenstecker. Ich habe mal versucht die relevanten Informationen aus dem Log herauszufischen:

`{"did":10007,"name":"Meteo Balcon","description":"","initialized":1,"position":0,"productName":"Actionneur pour moteur tubulaire Sonde d’ambiance DuoFern","serial":"69 09 21","statusesMap":
{"Position":0,"Manuellbetrieb":0},"status_changed":1555800124,"deviceGroup":2,"iconSet":{"name":"Sensor","description":"Generic Sensor Icon-Set","strMin":"An","strMax":"Aus","valMax":100,"valMin":0,"sprite":
{ "imageUri" : "images/sets/genericsensor-set.png", "numTiles" : 2 },"k":"iconset25"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"690921_1_A","visible":true,"groups" : [	] ,"favoredId":5013,"properties":
{"rain":3,"smartphone":3,"motion":3,"dusk":3,"smoke":3,"favored":0,"trigger":3,"manual":3,"sun":3,"generic":3,"closingContact":3,"temperature":3,"temperator":3,"warning":3,"dawn":3,"time":3,"dust":3,"wind":3,"states":[
{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setRainAuto","cfgId":109,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":0},
{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"setWindAuto","cfgId":111,"state":0},{"cfgKey":"setSunAuto","cfgId":105,"state":0},{"cfgKey":"setMorningAuto","cfgId":103,"state":0},
{"cfgKey":"setEveningAuto","cfgId":107,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},
{"cfgKey":"null","cfgId":0,"state":0}]},"sortId":0,"sTypes":[],"version":"1.0","sync":-2147372844,"messages":[],"hasErrors":0,"autos":[1,0,5,3,4,6,2]},

{"did":1010007,"name":"Prise Cuisine","description":"","initialized":1,"position":100,"productName":"Répéteur avec fonction de commutation Z-Wave","serial":"8","statusesMap":
{"Position":100,"Manuellbetrieb":0},"status_changed":1553487085,"deviceGroup":1,"iconSet":{"name":"Steckdose","description":"Steckdose Icon-Set","strMin":"An","strMax":"Aus","valMax":100,"valMin":0,"sprite":
{ "imageUri" : "images/sets/steckdose1.png", "numTiles" : 2 },"k":"iconset10"},"iconSetInverted":0,"paired":0,"statusValid":false,"uid":"ZW_138_8_8","visible":true,"groups" : [	 ] ,"favoredId":5014,"properties":
{"rain":3,"smartphone":3,"motion":3,"dusk":3,"smoke":3,"favored":0,"trigger":3,"manual":3,"sun":3,"generic":3,"closingContact":3,"temperature":3,"temperator":3,"warning":3,"dawn":3,"time":3,"dust":3,"wind":3,"states":[
{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":1},
{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setMorningAuto","cfgId":103,"state":1},{"cfgKey":"setEveningAuto","cfgId":107,"state":1},
{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0}]},"sortId":0,"sTypes":[],"version":"1.0","sync":-2147373516,"messages":[],"hasErrors":0,"autos":[0,2,3,1]},
`

Für den Umweltsensor steht da "actionneur pour moteur tubulaire" was komplett falsch ist, denn das wäre eine Rolladenmotor den ich nicht besitze. Ausserdem habe ich einen Rauchdetektor, der aber im Log nicht auftaucht.

**Comment by carbonide** [comment]
Thermostate funktionieren nach dem Update von heute, vielen Dank!
