### ISSUE TITLE
Rademacher Zwischenstecker

### ISSUE THREAD

**Issue by Smash89** [bombadiltom/homebridge-rademacher-homepilot#140]
Hallo, 

ich habe das Plugin jetzt schon einige Jahre Problemlos am laufen, und habe damit auch immer die Rademacher Zwischenstecker in HomeKit steuern können. Vor kurzem habe ich mir wieder zwei zusätzliche Zwischenstecker gekauft, die heißen ja jetzt Homepilot... Leider werden diese nicht mehr erkannt. Wissen Sie an was das liegt?

Vielen Dank!

**Comment by bombadiltom** [comment]
Dann hat es eine neue neue DeviceNumber, die bräuchte ich.
Siehe zB https://github.com/bombadiltom/homebridge-rademacher-homepilot/issues/138

**Comment by Smash89** [comment]
Danke für die schnelle Antwort, ich sehe nur am Stecker die ItemNo. 11301001 und im Homepilot die Version 4.7-1.

**Comment by Smash89** [comment]
Ach im Protokoll folgendes gefunden:

Unknown product: 16234511_S
Unknown product: 32501772_S
Unknown product: 99999981
nknown product: 99999984
Unknown product: 11301001

Da ist im Normalfall auch ein Bewegungsmelder mit dabei.

**Comment by bombadiltom** [comment]
Zwischenstecker sollten mit 0.10.10 erkannt werden
