### ISSUE TITLE
Cant set cronos to open rollotron window blinds

### ISSUE THREAD

**Issue by tottifacha2** [bombadiltom/homebridge-rademacher-homepilot#141]
Hi, I'm trying to set up a scheduled task to lower a blind using the following configuration:
```
{
    "debug": true,
    "tasks": [
        {
            "taskActive": true,
            "taskName": "Lower Persiana",
            "taskCronExpression": "0 20 * * *",
            "taskStateResetInterval": 0,
            "action": {
                "platform": "RademacherHomePilot",
                "service": "setPosition",
                "device": "Persiana",
                "position": 41
            },
            "onTrigger": "console.log('Persiana task triggered at: ' + new Date());"
        }
    ],
    "platform": "CronScheduler"
}
```
The name of the device in the accesories panel is Persiana but in the log says
` [RademacherHomePilot] blinds are online: Persiana [2]`
So first of all i dont even know what name to put, i tried both anyways on "device" and even tried using the id instead which is 2.
i always get in the log this error:
`[CronScheduler] [Bajar persiana] Get SensorState On -> CONTACT_DETECTED`
So at this stage i dont know what else to do, it seems that´s detecting the blinds as sensors but i dont understand why.
Sorry if i did a horrible mistake but im new to homebridge. Thank you for your time and assistance!

**Comment by bombadiltom** [comment]
You have to use automation to react on CONTACT_DETECTED, please read the documentation here https://github.com/uamanager/homebridge-cron-scheduler

BTW: this is not a question related to this plugin
