### ISSUE TITLE
Rademacher Thermostat shows Humidity Sensor

### ISSUE THREAD

**Issue by liebmar** [bombadiltom/homebridge-rademacher-homepilot#143]
First of all, thanks for your work, I really appreciate it! 

After updating from an older version of your plugin to a newer a one I recognised a new thermostat/heating-device-appearance in the Home App. Suddenly for all thermostats humidity sensors are displayed - with a default value of 50%. 

<img width="278" alt="Screenshot 2024-01-12 at 10 04 22" src="https://github.com/bombadiltom/homebridge-rademacher-homepilot/assets/66010542/aa358336-3d8f-494e-8071-f7a1e51e0f26">

My thermostats do not have humidty senosrs, so these exposed values to my home environment are false and conflict with the real values from actual dedicated humidity sensors (like the homepod minis or a netatmo station). 

Is there a way to add a line to the configuration file so that the thermostats to not expose these non existent humidity sensors?

Thanks a lot 
Marco

**Comment by bombadiltom** [comment]
no sorry, tried to remove it, but could only set the value to a fixed one
