### ISSUE TITLE
Keine Geräte mehr seit 11.1.2024

### ISSUE THREAD

**Issue by mirewa** [bombadiltom/homebridge-rademacher-homepilot#144]
Hi,
zumidest bei mir funktioniert die Briidge seit gester (11.1.2024) nicht mehr. Alle Versuche sie wieder zum Laufen zu bringen sind gescheitert. Änderungen habe ich zuvor keine vorgenommen. Alle Versionen sind auf dem aktuellsten Stand.
Das sind die entsprechenden Logeinträge
1/12/2024, 11:18:24 AMHomepilot BridgeERRORError loading plugin "homebridge-rademacher-homepilot"
1/12/2024, 11:18:24 AMHomepilot BridgeERRORInvalid or unexpected token
1/12/2024, 11:18:24 AMHomepilot BridgeWARNINGNo plugins installed.
1/12/2024, 11:18:24 AMHomepilot BridgeLoading 1 platforms...
1/12/2024, 11:18:24 AMHomepilot BridgeBridge is running on port 51846.

Habe nur ich das Problem?

**Comment by bombadiltom** [comment]
das ist ein node problem:
https://stackoverflow.com/questions/70958371/unexpected-token-when-trying-to-run-npm-install
