### ISSUE TITLE
Unknown Product 

### ISSUE THREAD

**Issue by Mcc2002** [bombadiltom/homebridge-rademacher-homepilot#146]
Garagentoröffner liefert in der Bridge einen Unknown Prodict Error 16901001

**Comment by bombadiltom** [comment]
als Rollade hinzugefügt, da das hier so aussieht, als ob es sich genauso verhält.
https://de.homepilot-smarthome.com/produkte/sicherheit-garage/garagentorantriebe/garagentorantrieb-premium-smart
Bitte testen...

**Comment by Mcc2002** [comment]
Habe es gerade getestet. Funktioniert zu 100%. Lieben Dank für die schnelle Hilfe.
