### ISSUE TITLE
Tür und Fenster Sensor

### ISSUE THREAD

**Issue by maagfly** [bombadiltom/homebridge-rademacher-homepilot#147]
Es gibt ein Problem mit dem Tür und Fenster Sensor von HomePilot dieser Triggert in der Home App bei geöffnet immer auf-zu auf-zu und das ununterbrochen. Also absolut nicht zu verwenden besonders bei Scenen oder als Auslöser. In der App von Rademacher ist es absolut normal und geht ohne Probleme. Gibt es eventuell ein Trick oder eine Einstellung damit er die Zustände in der Home App richtig wieder gibt.

**Comment by bombadiltom** [comment]
der funktioniert bei mir tadellos: https://www.rademacher.de/produkte/sicherheit-tore/sicherheitstechnik/duofern-fenster-tuerkontakt-9431

was sagt denn das Log?

**Comment by bombadiltom** [comment]
und was kommt hier? http://homepilot/v4/devices?devtype=Sensor

**Comment by maagfly** [comment]
Erstmal vielen lieben Dank für die Antwort.

Da sieht alles gut aus beim Aufruf über http://homepilot/v4/devices?devtype=Sensor

hier ein kleiner Ausschnitt 

{"response":"get_meters","meters":[{"description":"BalkontÃ¼r","deviceGroup":3,"did":32,"automations":[120],"readings":{"contact_state":"closed"},"batteryStatus":89,"batteryLow":false,"timestamp":1713985490,"iconSetInverted":1,"iconSet":{"k":"iconset12"},"name":"BalkontÃ¼r","statusValid":true,"deviceNumber":"14771002","uid":"ac984b_1","visible":true},{"description":"Fenster Badezimmer","deviceGroup":3,"did":34,"automations":[120],"readings":{"contact_state":"closed"},"batteryStatus":81,"batteryLow":false,"timestamp":1713686257,"iconSetInverted":0,"iconSet":{"k":"iconset24"},"name":"Fenster Badezimmer","statusValid":true,"deviceNumber":"14771002","uid":"ac983f_1","visible":true},{"description":"Fenster Schlafzimmer","deviceGroup":3,"did":36,"automations":[120],"readings":{"contact_state":"closed"},"batteryStatus":84,"batteryLow":false,"timestamp":1713691549,"iconSetInverted":0,"iconSet":{"k":"iconset24"},"name":"Fenster Schlafzimmer","statusValid":true,"deviceNumber":"14771002","uid":"ac984d_1","visible":true},{"description":"Sonnen Sensor","deviceGroup":3,"did":16,"automations":[30,140],"readings":{"sun_detected":false,"vibration_detected":false},"batteryLow":false,"timestamp":1713711780,"iconSetInverted":0,"iconSet":

Das Log von der Hombridge spielt ziemlich verrückt wie ich gerade feststellen muss wird ununterbrochen aktualisiert von Rademacher

![IMG_1949](https://github.com/bombadiltom/homebridge-rademacher-homepilot/assets/152656057/574d3734-704e-43bb-82af-452bd425866b)

Ich nutze auch die denk ich eigentlich Baugleichen von Homepilot https://de.homepilot-smarthome.com/produkte/sicherheit-garage/sicherheitstechnik/tuer-und-fensterkontakt-smart

**Comment by bombadiltom** [comment]
bitte einmal das Logfile downloaden und hier anhängen, so kann ich kein Problem erkennen

**Comment by maagfly** [comment]
Hallo, gibt es denn noch ein anderes Logfile ausser das in var/lip/homebridge.... bei dem sind keine Statusänderungen zu sehen.

Anbei das Log File
[homebridge.log](https://github.com/bombadiltom/homebridge-rademacher-homepilot/files/15104830/homebridge.log)

**Comment by bombadiltom** [comment]
nein, das ist schon korrekt, war denn eines der Fenster geöffnet?
