### ISSUE TITLE
Homepilot Premium Gateway - Keine Verbindung

### ISSUE THREAD

**Issue by Lentzus-Ger** [bombadiltom/homebridge-rademacher-homepilot#148]
Hallo zusammen,

ich habe hier schon fleißig gelesen und probiert. 
Leider schaffe ich es nicht, dass Homepilot Premium Gateway in Homebridge zu integrieren.

Ich habe es schon mit der IP Adresse mit /hp mit dem Gatewaynamen mit und ohne .local probiert. 
Nie kommt eine Verbindung zu stande.

Sieht jemand noch einen anderen Weg, wie ich meine Rolladensteuerung in HomeKit integrieren kann?

Lieben Dank!

**Comment by bombadiltom** [comment]
Was kommt denn im Browser unter der URL http://<IP-Adresse>/hp/v4/devices ?
