### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by eibi63** [bombadiltom/homebridge-rademacher-homepilot#149]
Funktionieren die Hutschienenaktoren Universaldimmer 9476-2 und Rohrmotor-Aktor 9471-3 mit dem Plugin?

**Comment by bombadiltom** [comment]
Universaldimmer 9476-2: ja, Artikelnummer 35200462, siehe https://www.rademacher.de/produkte/licht-heizung/lichtsteuerung/duofern-hutschienen-universaldimmer

Rohrmotor-Aktor 9471-3: noch nicht, Artikelnummer 35200662, füge ich hinzu
https://www.rademacher.de/produkte/rollladen-sonnenschutz/steuerung/duofern-hutschienen-motoraktor-9471-3

**Comment by eibi63** [comment]
Perfekt vielen Dank
