### ISSUE TITLE
Umweltsensor zeigt keine Minus-Temperaturen an

### ISSUE THREAD

**Issue by sg70** [bombadiltom/homebridge-rademacher-homepilot#15]
Außentemperatur: -5,3 Grad

Aktuelles Verhalten
Angezeigte Temperatur: 0,0 Grad

Erwartetes Verhalten
Anzeigte Temperatur: -5,5 Grad

**Comment by sg70** [comment]
PR #16 to fix the issue

**Comment by sg70** [comment]
fixed by PR #16

**Comment by modellbobby** [comment]
Hi SG70

könntest du die weiteren Sensoren in deinem homebridge Rademacher fork auslesen ? Wind, regen, sonnenstand. 

Danke für ein Feedback.
