### ISSUE TITLE
Getting Obstruction Detected ???

### ISSUE THREAD

**Issue by luissimoes** [bombadiltom/homebridge-rademacher-homepilot#19]
Sorry but I am not sure what this really means...
I see this in the log files for some shutters.... for others just the usual : eg "HWR shutters - Getting target position" or " Office Luis shutters - Setting target position: 100"

Here an excerpt of the "Status" cmd
May 24 09:16:21 raspberrypi homebridge[27692]: [5/24/2019, 9:16:21 AM] [RademacherHomePilot] HWR shutters - Getting obstruction detected
May 24 09:16:21 raspberrypi homebridge[27692]: [5/24/2019, 9:16:21 AM] [RademacherHomePilot] HWR shutters - Getting current position
May 24 09:16:21 raspberrypi homebridge[27692]: [5/24/2019, 9:16:21 AM] [RademacherHomePilot] Living Room Coffee shutters - Getting target position
May 24 09:16:21 raspberrypi homebridge[27692]: [5/24/2019, 9:16:21 AM] [RademacherHomePilot] Living Room Coffee shutters - Getting obstruction detected
May 24 09:16:21 raspberrypi homebridge[27692]: [5/24/2019, 9:16:21 AM] [RademacherHomePilot] Living Room Coffee shutters - Getting current position
May 24 09:16:21 raspberrypi homebridge[27692]: [5/24/2019, 9:16:21 AM] [RademacherHomePilot] Entry shutters - Getting target position
May 24 09:16:21 raspberrypi homebridge[27692]: [5/24/2019, 9:16:21 AM] [RademacherHomePilot] Entry shutters - Getting current position
May 24 09:16:21 raspberrypi homebridge[27692]: [5/24/2019, 9:16:21 AM] [RademacherHomePilot] Entry shutters - Getting obstruction detected

The shutters are **not** blocked and were not blocked

Many thanks

Luis

**Comment by bombadiltom** [comment]
"Getting obstruction detected" just tells us, that the status of obstruction is fetched from Homepilot (hasErrors in JSON), nothing more, so do not worry!

**Comment by luissimoes** [comment]
many thanks for the quick answer Tom! 
so... Homepilot is reporting errors?... because this happens sometimes, sometimes not, for some shutters yes, for some not... 

cheers!
Luis

**Comment by bombadiltom** [comment]
I do not know, if this can be seen in Homekit, just try to block some blinds ;-)
I did not add this feature...

**Comment by luissimoes** [comment]
ok! np... I was not sure what this means/meant!
Many thanks again!!!!

**Comment by clipse2004** [comment]
Hey Dude,

Got same error, how Block these blinds?
Because I got always a telegram message.
Big thanks

**Comment by bombadiltom** [comment]
"getting obstruction detected" is no error, just the information that the number of errors gets fetched.
A real error would be logged with: "obstruction detected: n errors" with n>0

**Comment by clipse2004** [comment]
But can I hide these message?

**Comment by bombadiltom** [comment]
No, it's just a log message, why do you get a telegram message for this?

**Comment by clipse2004** [comment]
Because I’m using reporter.service and logwatch :/

**Comment by bombadiltom** [comment]
then you have to define better rules
