### ISSUE TITLE
Switch Integration

### ISSUE THREAD

**Issue by Kohle81** [bombadiltom/homebridge-rademacher-homepilot#21]
Hello,

I don‘t know, if this device is working with your plugin?

DuoFern Mehrfachwandtaster BAT 9494-1 - Drahtloser & funkfähiger Mehrfachwandtaster für DuoFern Empfänger https://www.amazon.de/dp/B01NCHR4V9/ref=cm_sw_r_cp_api_i_MjUxDbF9815WB

Will it be possible to integrate this device?

It would be nice to use this switch in homekit 😜

Thanks for your great plugin!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bombadiltom** [comment]
I have this one https://service.rademacher.de/hc/de/sections/115001410649--DuoFern-Wandtaster-9494-
But I never found a reason to integrate it, why do you want to use it via homekit?

**Comment by Kohle81** [comment]
It would be great, so I could use the switch for other homitkit automation, if pressed the switch......

So I can use one switch for my blinds and the others for light oder fan activation....

**Comment by m4d-maNu** [comment]
The intrigration in HomeKit would be great.  Please do it if possible.

**Comment by bombadiltom** [comment]
I'll have a look, but Homebridge would have to poll at Homepilot and there definitely will be a delay between hitting the switch and the action

**Comment by YveliusNight** [comment]
Hello bombadiltom,

I guess I have a similar issue as Kohle81 but with the switch  (9473) [https://www.enobi.de/pdf/anleitungen/rademacher-empfaenger-9473-9474-anleitung.pdf](url).
The failure message is:
Unknown product: 31500162
{
:   description: 'Küche',
:   deviceGroup: 2,
:   did: 1010001,
:   hasErrors: 0,
:   iconSetInverted: 0,
:   iconSet: { k: 'iconset8' },
:   messages: [],
:   name: 'Küche Rohrmotor',
:   properties: {
:     closingContact: 3,
:     dawn: 3,
:     dusk: 3,
:     motion: 3,
:     rain: 3,
:     smartphone: 3,
:     smoke: 3,
:     sun: 3,
:     temperature: 3,
:     time: 2,
:     trigger: 3,
:     warning: 3,
:     wind: 3
:   },
:   statusValid: true,
:   statusesMap: { Manuellbetrieb: 0, Position: 100 },
:   visible: true,
:   deviceNumber: '31500162',
:   uid: '4703c3_1',
:   voiceControlledBy: ''

Would be nice if you can have a look also to this.  With  a RolloTron it is perfectly working :-)

**Comment by YveliusNight** [comment]
Great service. Is working now after update

**Comment by floriangutsfeld** [comment]
Hi, i use the switch and want its buildin relays in my homekit. Is it possible to integrate it?

**Comment by bombadiltom** [comment]
What's the devicenumber of the relays?

**Comment by floriangutsfeld** [comment]
Hi Tom, welche Nummer brauchst du? Die Artikel Nummer ist: 32501972 Bin gerade leider nicht zuhause um im Log navh zuschauen. 
Der Mehrfachwandtaster wird einmal als Taster und einmal als Licht etc. in HomePilot angezeigt. In der Homebridge tauchen sie unter den Geräten garnicht auf. Vielleicht hab ich ja auch einen Fehler gemacht 
Frohe Weihnachten,Flo
    	
    	

    	
    
  




On Tue, Dec 24, 2019 at 1:29 PM +0100, "Tom Lorenz" <notifications@github.com> wrote:












What's the devicenumber of the relays?

**Comment by floriangutsfeld** [comment]
Hallo Tom, ich hab jetzt mal ins Log reingeschaut. Momentane Configuration:Rademacher Mehrfachwandtaster Ralais vom WandtasterHue LED Strip über HomePilot
Im Log steht:Unknown product: 32501972_AUnknown product: 99999980Unknown product: 99999983
Ich hoffe damit kannst du was anfangen 

    	
    	

    	
    
  




On Tue, Dec 24, 2019 at 5:16 PM +0100, "floriangutsfeld" <floriangutsfeld@me.com> wrote:











  
  
  
    
    	Hi Tom, welche Nummer brauchst du? Die Artikel Nummer ist: 32501972 Bin gerade leider nicht zuhause um im Log navh zuschauen. 
Der Mehrfachwandtaster wird einmal als Taster und einmal als Licht etc. in HomePilot angezeigt. In der Homebridge tauchen sie unter den Geräten garnicht auf. Vielleicht hab ich ja auch einen Fehler gemacht 
Frohe Weihnachten,Flo
    	
    	

    	
    
  




On Tue, Dec 24, 2019 at 1:29 PM +0100, "Tom Lorenz" <notifications@github.com> wrote:












What's the devicenumber of the relays?

**Comment by BitSJ9** [comment]
Ich würde mich auch sehr freuen, den Wandtaster integriert zu haben. Aber ich benötige den 9494-2 230v Version der einen Aktor integriert hat.

**Comment by michaelkelch** [comment]
> Ich würde mich auch sehr freuen, den Wandtaster integriert zu haben. Aber ich benötige den 9494-2 230v Version der einen Aktor integriert hat.

der Aktor (!) des 9494-2 ist jetzt integriert.. wurde in 037d404 gelöst

**Comment by BitSJ9** [comment]
Ich habe diesen im Setup im Gebrauch.Gesendet mit der GMX iPhone AppAm 11.02.21 um 15:51 schrieb michael kelch
                
            
            
                
                    Von: "michael kelch" <notifications@github.com>Datum: 11. Februar 2021An: "bombadiltom/homebridge-rademacher-homepilot" <homebridge-rademacher-homepilot@noreply.github.com>Cc: "Comment" <comment@noreply.github.com>,"BitSJ9" <stefanjohanns@gmx.de>Betreff: Re: [bombadiltom/homebridge-rademacher-homepilot] Switch Integration (#21)
                
                



Ich würde mich auch sehr freuen, den Wandtaster integriert zu haben. Aber ich benötige den 9494-2 230v Version der einen Aktor integriert hat.



der Aktor (!) des 9494-2 ist jetzt integriert.. wurde in 037d404 gelöst



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/bombadiltom/homebridge-rademacher-homepilot/issues/21#issuecomment-777519976",

"url": "https://github.com/bombadiltom/homebridge-rademacher-homepilot/issues/21#issuecomment-777519976",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by BitSJ9** [comment]
> > Ich würde mich auch sehr freuen, den Wandtaster integriert zu haben. Aber ich benötige den 9494-2 230v Version der einen Aktor integriert hat.
> 
> der Aktor (!) des 9494-2 ist jetzt integriert.. wurde in [037d404](https://github.com/bombadiltom/homebridge-rademacher-homepilot/commit/037d4043486f17316fb703618c29fd4d9aa76c3a) gelöst

Hi, ich sehe den vermutlich den Aktor auch in der Home App, leider scheint er nicht zu Schalten.

**Comment by BitSJ9** [comment]
Ich habe den Container neu gestartet jetzt Funktionieren die Schalter. Super Job!
Danke

**Comment by bombadiltom** [comment]
Sieht schlecht aus für die Taster, der Status ist in der API nicht ersichtlich, könnte man höchstens über Dummy-Szenen erreichen, die von den Tastern angeschaltet und vom Plugin verarbeitet werden, mal sehen, ob sich diese Bastelei lohnt und überhaupt funktioniert.

Beschreibt doch einmal, was ihr dann mit dem Wandtaster machen wollen würdet, was nicht mit dem Homepilot selbst geht.

PS: Hat es jemand hinbekommen, mit dem 9494-2 Jalousien über eine Szene mit "Direkt" zu steuern? Hat bei mir nicht geklappt, mit dem batteriebetriebenen Wandtaster ging das problemlos.

**Comment by michaelkelch** [comment]
A) der Aktor der 9494-2 ist per homeBridge (und natürlich Plugin) ins Home „gespiegelt“ und wechselseitig sichtbar und schaltest...

B) die Taster sind natürlich nicht gespiegelt, doch können direkt Aktoren oder max 6 Scenen antriggern...

Die „Programmierung“ ist ein wenig „fummelig“ aber hat bei mir funktioniert 

Und ja, ich habe 2 Markisen direkt gesteuert- sieht Bild...

Was klappt denn nicht?

Von meinem iPhone gesendet

**Comment by BitSJ9** [comment]
Also ich habe Ihn so programmiert:
1) Die oberen beiden Tasten schalten den integrierten Aktor ( Eine Steckdose / in HomeKit sichtbar ) 
2) Die mittleren Tasten Schalten das Deckenlicht wo ein andere Aktor verbaut ist.
3) Die unteren Tasten Steuern direkt 2 Rollladenmotoren an. 

So habe ich alle Geräte in HomeKit sichtbar und Per Schalter steuerbar.

Also für mein Setup perfekt.

**Comment by michaelkelch** [comment]
Die 6 einzelnen Taster hatte ich auch schon jeweils mit einer Szene belegt..

 

Vorgehen:
Einen neuen Auslöser (!)  definieren
Hier dann „Sendersteuerung“ auswählen
Unter Sendersteuerung dann „ausgewählte Taste“ eine der 6 Push Taster auswählen 
Und nun final die Scene, die mit der Taste belegt sein soll auswählen
 

Das nun für bis zu 6 Tasten wiederholen und damit kann ich jeder Taste eine beliebige Funktion zuteilen..

 

Von: BitSJ9 <notifications@github.com>
Antworten an: bombadiltom/homebridge-rademacher-homepilot <reply@reply.github.com>
Datum: Sonntag, 28. Februar 2021 um 15:44
An: bombadiltom/homebridge-rademacher-homepilot <homebridge-rademacher-homepilot@noreply.github.com>
Cc: Michael Kelch <michael.kelch@t-online.de>, Comment <comment@noreply.github.com>
Betreff: Re: [bombadiltom/homebridge-rademacher-homepilot] Switch Integration (#21)

 

Also ich habe Ihn so programmiert:
Die oberen beiden Tasten schalten den integrierten Aktor ( Eine Steckdose / in HomeKit sichtbar )
Die mittleren Tasten Schalten das Deckenlicht wo ein andere Aktor verbaut ist.
Die unteren Tasten Steuern direkt 2 Rollladenmotoren an.
So habe ich alle Geräte in HomeKit sichtbar und Per Schalter steuerbar.

Also für mein Setup perfekt.

**Comment by bombadiltom** [comment]
Ja, danke, das geht alles, nur beim anderen Wandtaster gibt es zwei Kanäle mit jeweils Ein/Aus und zusätzlich den Tasten Auf/Ab und Stopp, wenn ich dann in der Szene die Jalousie mit Direkt eintrage, kann ich auch bei Jalouse die Lamellenposition steuern. Beim 230v Wandtaster scheint das der Antippmodus zu sein, den ich im Homepilot nicht konfigurieren kann

**Comment by bombadiltom** [comment]
auch wenn ich zwei Rolladenmotoren in einer Szene als "Direkt" angebe, ist die Steuerung sehr merkwürdig, muss man wirklich eine Szene für auf und eine für ab erstellen? Das hilft mir aber bei den Jalousien mit Lamellen nicht wirklich

**Comment by michaelkelch** [comment]
Zwei Motoren gleichzeitig auf einem „Schalterpaar“? 

Wenn es nur ein Motor ist, geht es? 

 

Und ist bei der Jalousie der Modus entsprechend ausgewählt?

 

 

Von: Tom Lorenz <notifications@github.com>
Antworten an: bombadiltom/homebridge-rademacher-homepilot <reply@reply.github.com>
Datum: Montag, 1. März 2021 um 09:49
An: bombadiltom/homebridge-rademacher-homepilot <homebridge-rademacher-homepilot@noreply.github.com>
Cc: Michael Kelch <michael.kelch@t-online.de>, Comment <comment@noreply.github.com>
Betreff: Re: [bombadiltom/homebridge-rademacher-homepilot] Switch Integration (#21)

 

auch wenn ich zwei Rolladenmotoren in einer Szene als "Direkt" angebe, ist die Steuerung sehr merkwürdig, muss man wirklich eine Szene für auf und eine für ab erstellen? Das hilft mir aber bei den Jalousien mit Lamellen nicht wirklich

**Comment by BitSJ9** [comment]
Also soweit ich mich erinnere, habe ich beide Motoren direkt an den Schalter angelernt ohne Homepilot (Szenen).
Also Anmeldemodus am Schalter gestartet und dann über den Homepilot den jeweiligen Rollladenmotor in den Anmeldemodus gebracht.
Vielleicht geht’s dann besser?
