### ISSUE TITLE
Tür-/Fensterkontakte

### ISSUE THREAD

**Issue by AWSW2017** [bombadiltom/homebridge-rademacher-homepilot#24]
Hallo,

kann man die Fenster-/Türkontakte als Geräte einbinden? 

Hintergrund: Neben dem üblichen Status, ob die Fenster/Türen geöffnet/geschlossen sind, verwende ich zusätzlich mehrere davon, um das ganze System auf die Jahreszeit, Urlaubszeit oder generell die Sonnenschutz- bzw. Automatik-Funktion aller Rollos umzuschalten. 

Beim Starten des Plugins werden sie als „unbekanntes Produkt“ (siehe Bild) erkannt, erscheinen aber nicht in HomeKit. Bisher habe ich die Kontakte anhand der folgenden Anleitung in ioBroker über den Parser integriert, aber nach dem Update auf die neue HomePilot Firmware funktioniert die Abfrage nicht mehr.

Hier der Link:
https://forum.smartapfel.de/forum/thread/2917-homepilot-in-homekit-mit-iobroker/

Danke für einen Tipp dazu. 😊

![09A5A2DA-0436-48E9-81BA-2940B2A6A65C](https://user-images.githubusercontent.com/34800740/65378763-a9f75880-dcbd-11e9-928e-3331655fcbfa.png)

**Comment by bombadiltom** [comment]
Habe selbst so einen hier rumliegen. Habe gerade einen Branch dazu angelegt, dauert aber noch ein wenig, bin momentan viel unterwegs...

**Comment by AWSW2017** [comment]
Hallo, 
kein Thema. Eilt nicht. Danke dafür vorab. 😁
PS: Einen Link zur direkten Abfrage zu kennen würde mir sehr helfen für eine Darstellung in ioBroker und in MagicMirror. 
Schönen Sonntag.

**Comment by bombadiltom** [comment]
http://homepilot/deviceajax.do?sensors=1 => http://homepilot/v4/devices?devtype=Sensor
http://homepilot/deviceajax.do?devices=1 => http://homepilot/v4/devices?devtype=Actuator
http://homepilot/deviceajax.do?device=<DID> => http://homepilot/v4/devices/<DID>

Bei Sensoren gibt es nur http://homepilot/devices/<DID>, eine Entsprechung zu
http://homepilot/deviceajax.do?meter=<DID> habe ich noch nicht gefunden

**Comment by AWSW2017** [comment]
Besten Dank. Schaue ich mir an. Viele Grüße

**Comment by bombadiltom** [comment]
Türkontakt sind in 0.3.0 implementiert, da es aber nur zwei Zustände auf Homekit-Seite gibt, wird kein gekipptes Fenster erkannt.

**Comment by AWSW2017** [comment]
Hallo! Dankeschön. Wie kann ich die Version erhalten? Nach dem Update bin ich weiter auf 0.25... danke

**Comment by bombadiltom** [comment]
Hab's gerade gepublished

**Comment by AWSW2017** [comment]
Hi und danke! Habe 0.30 installiert aber ich sehe keine Tür-/Fensterkontake... 😢 Weder in Homebridge noch in ioBroker...

**Comment by AWSW2017** [comment]
Sorry... Meine HomeKit... nicht Homebridge...

**Comment by bombadiltom** [comment]
dann müssten noch unknown devices im log stehen, da bräuchte ich die device numbers

**Comment by AWSW2017** [comment]
Hi,

hier die Nummern als Auszug aus dem Log:

Smartphone:
[2019-10-13 15:45:41] [RademacherHomePilot] { description: 'iPhone X',
[2019-10-13 15:45:41] [RademacherHomePilot] Unknown product: 99999998

Türkontakt:
[2019-10-13 15:45:41] [RademacherHomePilot] { description: 'ZU gleich Automatik Funktion AN',
[2019-10-13 15:45:41] [RademacherHomePilot] Unknown product: 32002119

Rollos (waren vorher bekannte Geräte, meine ich):
[2019-10-13 15:45:41] [RademacherHomePilot] { description: 'Wohnzimmer Rollo 1',
[2019-10-13 15:45:41] [RademacherHomePilot] Unknown product: 16234511_S

Vielen Dank vorab.

Viele Grüße

**Comment by bombadiltom** [comment]
Türkontakt und Rollos habe ich in 0.3.1 ergänzt, aber wie kommt das iPhone da rein?

**Comment by AWSW2017** [comment]
Cool 😎 Danke, die Kontakte sehe ich nun in HomeKit als auch in ioBroker 😁 Vielen Dank.

Die Rollos werden weiter als „unknown product“ im Startlog gelistet, funktionieren aber 1a.

Das iPhone kommt da als in HomePilot angelegtes Gerät rein und hat zusätzlich die GeoPilot App. So kann ich wenn ich bestimmte Wege/Bereiche lang fahre automatisch Aktionen auslösen, noch weit bevor ich zu Hause ankomme (Heizung, Rollos, Licht)... 

Danke Dir und schönen Abend noch.

**Comment by bombadiltom** [comment]
Haben die Rollos auch Lichtsensoren?

**Comment by AWSW2017** [comment]
Hallo, ja haben alle den LWL Anschluss. Bei 2 davon nutze ich die Lichtsensoren...

PS: Kann man bei den Türkontakten noch den Akkustand auslesen? 

Danke vorab.

**Comment by AWSW2017** [comment]
Hallo,
danke noch mal. Funktioniert auch mit der neuen Rademacher Firmware echt gut. 
Viele Grüße!
