### ISSUE TITLE
Version 0.2.0 no automatic, Rademacher Actor klicks every Minute

### ISSUE THREAD

**Issue by Wilhelm111** [bombadiltom/homebridge-rademacher-homepilot#25]
Same Problem like First Vision.

1.) Rollos Closing as programmed, but after about 10 Seconds all will run open.

2.) One  Rademacher Aktor Relais klicks once per Minute when the Rollo ist 0% or 100%. 

Need help pls

**Comment by bombadiltom** [comment]
Please reinstall published version 0.20, the it should be gone because I removed the whole interval thing because of such behaviour

**Comment by Wilhelm111** [comment]
Hallo Tom,

bin mit dem Raspberry noch nicht so fit.
Kannst du mir die Terminal Comands fürs Reinstalling geben? :)

**Comment by Wilhelm111** [comment]
Da der Fehler im Plugin bleibt, schalte ich die Homebridge mal ab.
