### ISSUE TITLE
RolloPort SX5

### ISSUE THREAD

**Issue by UrsLebowski** [bombadiltom/homebridge-rademacher-homepilot#28]
Hallo,
Gibt es eine Möglichkeit den Garagentoröffner in HomeKit anzeigen zu lassen?

LG

Urs

**Comment by bombadiltom** [comment]
Könnte man als Schalter einbinden, dazu bräuchte ich die Devicenumber

**Comment by Manni864** [comment]
Hallo, habe auch den RolloPort, der nicht erkannt wird.
Müsste die Device-Nr. 45059071 sein:
[10/3/2019, 2:59:51 PM] [RademacherHomePilot] Unknown product: 45059071

**Comment by basti2oo2** [comment]
Hallo, vielen Dank soweit! Mein SX5 wird jetzt als Schalter angezeigt, lässt sich aber leider nicht steuern. Wenn das Tor geschlossen ist, wird der Schalter als „ein“ angezeigt. Wenn ich ihn dann auf „aus“ stelle, passiert nichts. Besteht die Möglichkeit, den SX5 als Jalousie einzubinden, analog zu den Rolladenmotoren? Grundsätzlich lässt sich der SX5 ja auch so steuern, d.h. z.B. prozentual öffnen und schließen.

**Comment by basti2oo2** [comment]
Mit der neuen Version bekomme ich eine Fehlermeldung:
2019-10-5 09:12:21] [RademacherHomePilot] Successfully logged into HomePilot. 
[2019-10-5 09:12:21] [RademacherHomePilot] blinds are online: Garagentor [1010008] /usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/ 
RademacherBlindsAccessory.js:25 
.getCharacteristictglobal.Characteristic.CurrentPosition) 
TypeError: Cannot read property 'getCharacteristic' of undefined at new RademacherBlindsAccessory (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/ accessories/RademacherBlindsAccessory.js:25:10) at/usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:55:58 at Array.forEach (<anonymous>) at handleActuators (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:43:34) at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/ 
RademacherHomePilotSession.jsinyilS) at Request.self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/ request/request.js:185:22) at Request.emit (events.js:188:13) at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/ request/request.js:1161:10) at Request.emit (events.js:188:13) at lncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/ node_modules/request/request.js:1083:12) at Object.onceWrapper (events.js:276:13) at IncomingMessage.emit (events.js:193:15) at endReadableNT (_stream_readable.js:1129:12) at process.internalTickCallback (internal/process/next_tick.js:72:19) pi@raspberrypi:~$

**Comment by bombadiltom** [comment]
Dann bitte mal den Output von http://<homepilot-ip>/v4/devices/1010008 hier posten. Danke.

**Comment by bombadiltom** [comment]
Oder folgendes versuchen:
rm -f /etc/homebridge/accessories/cachedAccessories

**Comment by basti2oo2** [comment]
Danke fürs schnelle Kümmern!
Das Entfernen der cachedAccessories hat nicht geholfen.
Hier der Output:
{"response":"get_device","device":{"description":"Garagentor","deviceGroup":8,"did":1010008,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset30"},"messages":[],"name":"Garagentor","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":100},"visible":true,"deviceNumber":"45059071","uid":"4e0f9b_1","voiceControlledBy":"","sceneConfig":["DIRECT_FUNCTION_CMD","GOTO_POS_CMD","POS_DOWN_CMD","AUTO_MODE_CFG"]}}

**Comment by bombadiltom** [comment]
sieht gut aus für Einbindung als Blinds,
dann /etc/homebridge/persist löschen, denn dort ist es jetzt als Switch drin

**Comment by basti2oo2** [comment]
Mega! Funktioniert bestens! Ganz herzlichen Dank! 👍

**Comment by Manni864** [comment]
Vielen dank, nachdem ich das System komplett neu aufgesetzt habe funktioniert der RolloPort auch  bei mir👍. 
Jetzt habe ich nur noch Fehlermeldungen beim Umweltsensor, die Werte werden leider nicht angezeigt.

**Comment by bombadiltom** [comment]
Welche Fehlermeldungen? Bitte logs schicken!

**Comment by bombadiltom** [comment]
Und bitte http://<homepilot>/v4/devices/<did> für alle Geräte im Umweltsensor,
und auch http://<homepilot>/devices/<did>

**Comment by UrsLebowski** [comment]
Funktioniert Wunderbar! Kam gerade erst dazu es zu testen. Vielen Dank für die schnelle Umsetzung!!! Wünsche ein schönes Restwochenende:)

**Comment by Manni864** [comment]
[Log_Hoobs.docx](https://github.com/bombadiltom/homebridge-rademacher-homepilot/files/3694684/Log_Hoobs.docx)
Logfile mit Fehlermeldung. Sobald die Werte vom Umweltsensor ausgelesen werden sollen startet Homebridge neu.
