### ISSUE TITLE
Homebridge stoppt seit heute

### ISSUE THREAD

**Issue by martak101** [bombadiltom/homebridge-rademacher-homepilot#36]
Hallo,
leider habe ich seit heute das Problem, dass die Homebridge nach zunächst erfolgreichem Start kurze Zeit später gestoppt wird.
Starte ich die Bridge jedoch im Debugmodus ist alles ok.

Ich bin hier gerade etwas ratlos.
Was kann ich tun, um die Ursache für das Verhalten zu finden. Welche Logs kann ich erzeugen bzw. zur Verfügung stellen?

**Comment by bombadiltom** [comment]
was steht in /var/log/syslog nach dem Stop?

**Comment by martak101** [comment]
Hallo Tom,
habe das Problem gerade finden und beheben können.
Es hatte nichts mit dem Plugin zu tun.
Ursache war, dass, warum auch immer, die Logfiles nicht mehr geschrieben werden konnten, da der Besitzer plötzlich root war.

Können somit hier schliessen.

Vielen Dank
