### ISSUE TITLE
Fertige Szenen als Schalter anzeigen.

### ISSUE THREAD

**Issue by UrsLebowski** [bombadiltom/homebridge-rademacher-homepilot#37]
Hallo, ich habe ein selbst konstruiertes VorhangSystem für ein großes Glas-Giebelfenster. Beim öffnen und Schließen wird es von zwei Gurtwicklern angetrieben, die gegegneinander laufen. D,h, wenn geschlossen werden soll, dann läuft einer auf, der anderen zu. Beim öffnen umgekehrt. Dazu gibt es im HomePilot je eine Szene. Jetzt würde ich gern die Szenen als Schalter zu HomeKit durchschleifen und gar nicht unbedingt die Gurtwickler selbst. Beim Harmony Plugin ist das auch so machbar. Gibts da eine Möglichkeit?

LG

Urs

**Comment by bombadiltom** [comment]
Szenen wollte ich immer schon einbauen :-)
Published in 0.4.0

**Comment by UrsLebowski** [comment]
Hi, funktioniert super! Danke für das schnelle Umsetzten! Liebe Grüße und schönes Weihnachtsfest! Urs!
