### ISSUE TITLE
Evtl. Geräteerweiterung RP-SX5-HS-RF11 RolloPort Codierschaltgerät Funk

### ISSUE THREAD

**Issue by UrsLebowski** [bombadiltom/homebridge-rademacher-homepilot#38]
Hallo,
Ich schon wieder:) ich hoffe dich stören die Anfrage nicht! Aber bei der letzten hatte  ich dich ja zur Erfüllung eines eigenen lang gehegten Wunsches motiviert🤗Ist   es möglich den oben genannten Schalter einzubinden? Als einfacher switch wäre ausreichend.  Wenn ja, was brauchst du von mir, was kann ich liefern? Wünsche schon mal ein wunderschönes Weihnachtsfest!
LG
Urs

**Comment by bombadiltom** [comment]
Ich bräuchte die Devicenumber, sollte jetzt als "Unknown Product" im log stehen.
Auch dir ein frohes Fest!

**Comment by UrsLebowski** [comment]
Hallo,
Danke für die schnelle Rückmeldung. Da habe ich mich wohl zu früh gefreut! Ich bekomme das Codier-SchaltGerät nicht mit meinem HomePilot gekoppelt. Der Garagentorantrieb ist im Home Pilot. Das Codier-SchaltGerät allerdings direkt mit dem Garagentorantrieb gekoppelt. Der Versuch des Codier-SchaltGerät am HomePilot anzumelden ist mehrfach gescheitert. Muss jetzt mal im Internet suchen oder den Support anschreiben, ob das überhaupt vorgesehen ist. Trotzdem erst mal danke für die schnelle Hilfe.  Noch einen schönen Feiertag:)
LG Urs
