### ISSUE TITLE
Siri "Gerät reagiert nicht" wenn ein Gerät eingeschaltet werden soll, dass schon an ist

### ISSUE THREAD

**Issue by irstmon** [bombadiltom/homebridge-rademacher-homepilot#4]
Hi,

Wenn man per Siri z.B. eine Lampe einschalten möchte die schon eingeschaltet ist kommt ein Timeout mit "Dein Gerät <xyz> reagiert nicht":

```
[2018-7-22 08:37:17] [RademacherHomePilot] Lampe3 - Setting switch: true
[2018-7-22 08:37:17] [RademacherHomePilot] Lampe3 - switch changed=false
```
Anschließend gibt es eine Zeit lang Probleme das gleiche oder andere Geräte zu steuern eh sich das ganze wieder "fängt"

**Comment by bombadiltom** [comment]
Oh: Wenn sich am Status nichts ändert, wird das callback nicht aufgerufen, das ist anscheinend nicht gut...
