### ISSUE TITLE
Scenes not working

### ISSUE THREAD

**Issue by shroudy86** [bombadiltom/homebridge-rademacher-homepilot#42]
Hello,

first i would like to thank you for the great plugin.

I‘ve got one little question with the new scene switch:

Is there a way to hide this new switch? I don‘t really need it 🤔. And it seems not working in my Home App too. So i just have one useless Switch at my Home 😅.

It would ne great if there is a option to disable the Switch so it‘s not longer visible in the Home App 😃.

Thank you so much.

Best regards

Patrick

**Comment by bombadiltom** [comment]
added switch for scenes and only adding scenes with isExecutable=1 now
