### ISSUE TITLE
New issue Rademacher HomePilot Sigterm on Homebridge

### ISSUE THREAD

**Issue by ApplesandPears** [bombadiltom/homebridge-rademacher-homepilot#43]
Hi bobadiltom,

I have an issue with my homebridge-rademacher-homepilot. I can't remember of a change, just made a reboot of my NAS and of Homepilot and homebridge is now shutting down when starting the container.

Log:

2020-03-03 20:05:08 | stdout | [37m[3/3/2020, 8:05:08 PM][39m Got SIGTERM, shutting down Homebridge...
-- | -- | --
2020-03-03 20:05:08 | stdout | at Timer.processTimers (timers.js:223:10)[39m[22m
2020-03-03 20:05:08 | stdout | at listOnTimeout (timers.js:263:5)
2020-03-03 20:05:08 | stdout | at tryOnTimeout (timers.js:300:5)
2020-03-03 20:05:08 | stdout | at ontimeout (timers.js:436:11)
2020-03-03 20:05:08 | stdout | at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
2020-03-03 20:05:08 | stdout | at Request.emit (events.js:189:13)
2020-03-03 20:05:08 | stdout | at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
2020-03-03 20:05:08 | stdout | at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:115:13)
2020-03-03 20:05:08 | stdout | at handleSensors (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:124:29)
2020-03-03 20:05:08 | stdout | [37m[3/3/2020, 8:05:08 PM][39m [1m[31mError: Request failed: Error: ETIMEDOUT
2020-03-03 20:05:08 | stdout | [37m[3/3/2020, 8:05:08 PM][39m [36m[RademacherHomePilot][39m GET error for path http://192.168.1.xx/v4/devices?devtype=Sensor: Error: ETIMEDOUT
2020-03-03 20:05:08 | stdout | at Timer.processTimers (timers.js:223:10)[39m[22m
2020-03-03 20:05:08 | stdout | at listOnTimeout (timers.js:263:5)
2020-03-03 20:05:08 | stdout | at tryOnTimeout (timers.js:300:5)
2020-03-03 20:05:08 | stdout | at ontimeout (timers.js:436:11)
2020-03-03 20:05:08 | stdout | at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
2020-03-03 20:05:08 | stdout | at Request.emit (events.js:189:13)
2020-03-03 20:05:08 | stdout | at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
2020-03-03 20:05:08 | stdout | at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:115:13)
2020-03-03 20:05:08 | stdout | at handleActuators (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:40:29)
2020-03-03 20:05:08 | stdout | [37m[3/3/2020, 8:05:08 PM][39m [1m[31mError: Request failed: Error: ETIMEDOUT
2020-03-03 20:05:08 | stdout | [37m[3/3/2020, 8:05:08 PM][39m [36m[RademacherHomePilot][39m GET error for path http://192.168.1.xx/v4/devices?devtype=Actuator: Error: ETIMEDOUT
2020-03-03 20:05:03 | stdout | [37m[3/3/2020, 8:05:03 PM][39m Homebridge is running on port 51826.

When I lookup http://192.168.1.xx/v4/devices?devtype=Sensor: (or Actuator), I get a result from Homepilot. **For Sensor, result is:** 
{"response":"get_visible_devices","devices":[{"description":"Rolladen Kueche  (Google)","deviceGroup":2,"did":1,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Kueche","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705c77_A_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Heizung Wohnzimmer","deviceGroup":5,"did":3,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Heizung Wohnzimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":40,"acttemperatur":235,"relaisstatus":0,"automaticvalue":235,"manualoverride":100},"visible":true,"deviceNumber":"32501812_A","uid":"7310e1_A_1","voiceControlledBy":"","origin":"HomePilot","posMin":40,"posMax":400},{"description":"Rolladen Terrasse (Google)","deviceGroup":2,"did":5,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Terrasse","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705c71_A_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Rolladen Wohnzimmer (Google)","deviceGroup":2,"did":7,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Wohnzimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705ec0_A_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Heizung WC","deviceGroup":5,"did":9,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Heizung WC","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":40,"acttemperatur":237,"relaisstatus":0,"automaticvalue":215,"manualoverride":100},"visible":true,"deviceNumber":"32501812_A","uid":"7311cb_A_1","voiceControlledBy":"","origin":"HomePilot","posMin":40,"posMax":400},{"description":"Rolladen Bad (Google)","deviceGroup":2,"did":11,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Bad","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705eba_A_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Heizung Bad","deviceGroup":5,"did":13,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Heizung Bad","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":40,"acttemperatur":227,"relaisstatus":0,"automaticvalue":240,"manualoverride":100},"visible":true,"deviceNumber":"32501812_A","uid":"7310e8_A_1","voiceControlledBy":"","origin":"HomePilot","posMin":40,"posMax":400},{"description":"Heizung Schlafzimmer","deviceGroup":5,"did":15,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Heizung Schlafzimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":40,"acttemperatur":218,"relaisstatus":0,"automaticvalue":220,"manualoverride":100},"visible":true,"deviceNumber":"32501812_A","uid":"7310b1_A_1","voiceControlledBy":"","origin":"HomePilot","posMin":40,"posMax":400},{"description":"Rolladen Schlafzimmer (Google)","deviceGroup":2,"did":17,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Schlafzimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705eb2_A_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Heizung Arbeitszimmer","deviceGroup":5,"did":19,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Heizung Arbeitszimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":40,"acttemperatur":218,"relaisstatus":0,"automaticvalue":220,"manualoverride":100},"visible":true,"deviceNumber":"32501812_A","uid":"73119c_A_1","voiceControlledBy":"","origin":"HomePilot","posMin":40,"posMax":400},{"description":"Rolladen Arbeitszimmer (Google)","deviceGroup":2,"did":21,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Arbeitszimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705d51_A_1","voiceControlledBy":"","origin":"HomePilot"}]}

**For Actuator, result is:**
{"response":"get_visible_devices","devices":[{"description":"Rolladen Kueche  (Google)","deviceGroup":2,"did":1,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Kueche","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705c77_A_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Heizung Wohnzimmer","deviceGroup":5,"did":3,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Heizung Wohnzimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":40,"acttemperatur":235,"relaisstatus":0,"automaticvalue":235,"manualoverride":100},"visible":true,"deviceNumber":"32501812_A","uid":"7310e1_A_1","voiceControlledBy":"","origin":"HomePilot","posMin":40,"posMax":400},{"description":"Rolladen Terrasse (Google)","deviceGroup":2,"did":5,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Terrasse","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705c71_A_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Rolladen Wohnzimmer (Google)","deviceGroup":2,"did":7,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Wohnzimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705ec0_A_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Heizung WC","deviceGroup":5,"did":9,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Heizung WC","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":40,"acttemperatur":237,"relaisstatus":0,"automaticvalue":215,"manualoverride":100},"visible":true,"deviceNumber":"32501812_A","uid":"7311cb_A_1","voiceControlledBy":"","origin":"HomePilot","posMin":40,"posMax":400},{"description":"Rolladen Bad (Google)","deviceGroup":2,"did":11,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Bad","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705eba_A_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Heizung Bad","deviceGroup":5,"did":13,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Heizung Bad","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":40,"acttemperatur":227,"relaisstatus":0,"automaticvalue":240,"manualoverride":100},"visible":true,"deviceNumber":"32501812_A","uid":"7310e8_A_1","voiceControlledBy":"","origin":"HomePilot","posMin":40,"posMax":400},{"description":"Heizung Schlafzimmer","deviceGroup":5,"did":15,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Heizung Schlafzimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":40,"acttemperatur":218,"relaisstatus":0,"automaticvalue":220,"manualoverride":100},"visible":true,"deviceNumber":"32501812_A","uid":"7310b1_A_1","voiceControlledBy":"","origin":"HomePilot","posMin":40,"posMax":400},{"description":"Rolladen Schlafzimmer (Google)","deviceGroup":2,"did":17,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Schlafzimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705eb2_A_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Heizung Arbeitszimmer","deviceGroup":5,"did":19,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Heizung Arbeitszimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":40,"acttemperatur":218,"relaisstatus":0,"automaticvalue":220,"manualoverride":100},"visible":true,"deviceNumber":"32501812_A","uid":"73119c_A_1","voiceControlledBy":"","origin":"HomePilot","posMin":40,"posMax":400},{"description":"Rolladen Arbeitszimmer (Google)","deviceGroup":2,"did":21,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rolladen Arbeitszimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"36500572_A","uid":"705d51_A_1","voiceControlledBy":"","origin":"HomePilot"}]}

Can you see from this already where the issue comes from?

Thanks in advance for your help.
ApplesandPears

**Comment by ApplesandPears** [comment]
One additional comment. I had to reset the network settings from my Synology, but re-configured the bond and configured again fixed IP (fixed IP for both, Syno and HomePilot). Synology got a new fixed IP. Don't think this has something to do with Network config, but who knows...

**Comment by bombadiltom** [comment]
ETIMEDOUT is a network problem, the plugin cannot connect to the homepilot for some reason
