### ISSUE TITLE
[Rademacher HomePilot] Unknown product: 23602075

### ISSUE THREAD

**Issue by Jamires79** [bombadiltom/homebridge-rademacher-homepilot#44]
Hallo Tom,
ich habe das Problem das mein SLDM 20/16PZ Rademacher DuoFern Funk-Rohrmotor nicht in Homebridge und deshalb auch nicht in HomeKit erscheint!

Grüße Markus

**Comment by bombadiltom** [comment]
Halo Markus,

sollte in Release 0.4.2 enthalten sein.
Bite testen...

Gruß,
Tom

**Comment by Jamires79** [comment]
Vielen Dank!
Getestet und läuft!
