### ISSUE TITLE
Neues einlesen der Szenen etc.

### ISSUE THREAD

**Issue by fritte87** [bombadiltom/homebridge-rademacher-homepilot#49]
Hi,
ich betreibe die Homebridge mit deinem Plugin auf meinem Rasperry.
Ich habe nun Szenen auf dem Rademacher gelöscht, diese bleiben jedoch in der Homebridge vorhanden. des Weiteren fügen sich die neuen Szenen irgendwie nicht korrekt ein.
Was kann ich hier machen?

Danke

**Comment by bombadiltom** [comment]
accessories/cachedAccessories löschen

**Comment by fritte87** [comment]
Hi,
danke für den Kommentar...allerdings klappt das löschen der Datei nicht so Recht...
Ich lösche die entsprechende Datei, roboote die Homebridge...die Szenen sind jedoch weiterhin die alten...

muss man noch was löschen?

Danke

**Comment by bombadiltom** [comment]
ggf. noch persist/*, ansonsten einmal die Bridge aus dem Haus entfernen

**Comment by fritte87** [comment]
Guten Morgen und vielen Dank für die schnelle Info...
Wenn ich den Ordner persist entferne...dann ist die Homebridge nicht mehr sauber zu erreichen...
wenn ich den Ordner persist/* lösche....müsste ich aber auch alle anderen Geräte neu einrichten, oder?
Ich habe knapp 30 Shellys noch über ein anderes Plugin am laufen...

Danke
