### ISSUE TITLE
Passwort im Klartext

### ISSUE THREAD

**Issue by timwegenerDE** [bombadiltom/homebridge-rademacher-homepilot#51]
Hallo,

aktuell habe ich das Homepilot-Passwort im Klartext eingetragen. Im Code sehe ich, dass dieses noch gehashed wird. Gäbe es hier die Möglichkeit direkt das PW in SHA256 einzutragen und dies via Config „useHashed“ o.ä. anzugeben?

**Comment by bombadiltom** [comment]
Hallo, so wie ich das sehe, wird das Passswort mit einem Salt, der vom Homepilot kommt, gehasht, keine Ahnung, ob der immer gleich ist. Müsste man mal ausprobieren.

**Comment by timwegenerDE** [comment]
Wird es nicht einmal gehashed und später wird dieser Hash + Salt noch einmal gehashed? Das erste Hashen ließe sich m.E. sparen, wenn das PW in der Config bereits als SHA256 vorliegt?

**Comment by bombadiltom** [comment]
stimmt, rel 0.4.7

**Comment by timwegenerDE** [comment]
Noch ein Hinweis, wenn jemand über diesen Issue stolpert:
Das Passwort muss SHA265 gehashed werden und im Hex-Format vorliegen.

Das geht z.B. hier: https://www.conversion-tool.com/sha256/
ACHTUNG: Passwörter auf Webseiten eingeben birgt immer Gefahren! Ich kann keine Aussage über die Seriosität der o.a. Webseite machen!

**Comment by stkhome** [comment]
Hallo Bombadiltom,

vllt. kannst Du mir helfen.
Ich habe einen alten Rademacher Homepilot (1) mit Fw 4.6.6 (letzte die auf dem 1‘er geht).
Welche Plugin-Version läuft mit dieser FW-Version?
Mit der neuesten kann ich den Homepilot leider nicht ansprechen.

Danke für Deine Hilfe.

Gruß

**Comment by bombadiltom** [comment]
Hmmm.... woran erkennt man die Version der Homepilot? Habe meinen seit 3 Jahren und betreibe ihn mit FW 5.1.8. 
Die 4er FW funktioniert bis https://www.npmjs.com/package/homebridge-rademacher-homepilot/v/0.1.1

**Comment by stkhome** [comment]
Erkennen kann man die Version des Homepilot am besten an der Farbe. Weiß=Homepilot 1 (Fw 4.6.6) und schwarz=Homepilot 2.
Danke für Deine Hilfe, werde die Version 0.1.1 mal probieren.

Gruss

**Comment by clipse2004** [comment]
kann mir jemand verraten wie ich das sog. hashed passwort aktivieren kann? Im HomePiloten gibts dazu keine Option bzw. finde ich die nicht

**Comment by timwegenerDE** [comment]
Das ist der „normale“ Passwortschutz im Homepilot. Auf Seiten dieses Plugins kann dann anstatt dieses Passworts im Klartext ein gehashtes Passwort eingetragen werden. Das ist im Prinzip das Passwort in verschlüsselter Form (Jajaja ich weiss Hash ist keine Verschlüsselung). Weiter oben hatte ich eine Webseite gepostet auf der Sie aus dem Klartext-Passwort die gehashte Variante erzeugen können.

**Comment by tassilo-net** [comment]
> Hallo Bombadiltom,
> 
> vllt. kannst Du mir helfen. Ich habe einen alten Rademacher Homepilot (1) mit Fw 4.6.6 (letzte die auf dem 1‘er geht). Welche Plugin-Version läuft mit dieser FW-Version? Mit der neuesten kann ich den Homepilot leider nicht ansprechen.
> 
> Danke für Deine Hilfe.
> 
> Gruß

Hi @stkhome 
hast du die Firmware in einem Format um sie weiterzugeben? Es gab ja mal den HomePilot® 1 Upgrade Stick. Leider bietet Rademacher den nicht mehr an. Hast du den vielleicht und könntest von dem ein Image machen? Oder hast du eine andere Möglichkeit die Firmware weiterzugeben? Das wäre wirklich mega und eine große Hilfe.
