### ISSUE TITLE
After updating it didn’t work anymore

### ISSUE THREAD

**Issue by clipse2004** [bombadiltom/homebridge-rademacher-homepilot#55]
Hi,
Today I updated your plugin and now I got these error:
„TypeError: accessory.getService is not a function“ 
Im Running Hoobs.

Did you change anything for Homebridge 1.0?

**Comment by bombadiltom** [comment]
please provide logs

**Comment by ebreg** [comment]
Unfortunately I get the same error after the update. Homebridge always restarts itself after the error. Below you can find the relevant parts of the log:

## Homebridge.log

> [7/4/2020, 22:05:13] Loaded plugin: homebridge-rademacher-homepilot@0.4.8
> [7/4/2020, 22:05:13] Registering platform 'homebridge-rademacher-homepilot.RademacherHomePilot'
> [7/4/2020, 22:05:13] ---
> [7/4/2020, 22:05:14] [RademacherHomePilot] Initializing RademacherHomePilot platform...
> [7/4/2020, 22:05:23] [RademacherHomePilot] Successfully logged into HomePilot.
> [7/4/2020, 22:05:24] [RademacherHomePilot] door sensor is online: Terassentür [1010012]
> [7/4/2020, 22:05:24] TypeError: accessory.getService is not a function
>     at RademacherDoorSensorAccessory.RademacherAccessory (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:2:26)
>     at new RademacherDoorSensorAccessory (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherDoorSensorAccessory.js:5:25)
>     at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:180:58
>     at Array.forEach (<anonymous>)
>     at handleSensors (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:136:33)
>     at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:119:13)
>     at Request.self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:315:20)
>     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:315:20)
> [7/4/2020, 22:05:24] [RademacherHomePilot] blinds are online: Rollo Schlafzimmer [1010007]
> [7/4/2020, 22:05:24] TypeError: accessory.getService is not a function
>     at RademacherBlindsAccessory.RademacherAccessory (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:2:26)
>     at new RademacherBlindsAccessory (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherBlindsAccessory.js:5:25)
>     at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:59:58
>     at Array.forEach (<anonymous>)
>     at handleActuators (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:47:34)
>     at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:119:13)
>     at Request.self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:315:20)
>     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:315:20)
> [7/4/2020, 22:05:24] Got SIGTERM, shutting down Homebridge...



## Environment
**Host system:** Raspberry Pi Zero WH
**Running method:** Raspbian (Homebridge Raspberry Pi Image)
** Plugin version:** 0.4.8
**Homebridge version:** 1.1.1
**Node.js version:** 12.18.1
