### ISSUE TITLE
Error after installing „Umweltsensor“

### ISSUE THREAD

**Issue by clipse2004** [bombadiltom/homebridge-rademacher-homepilot#56]
Hello,
Yesterday I installed the new sensor, I didn’t change anything and now I got these error:

25.7.2020, 13:12:22 [HomePilot] GET error for path http://192.168.178.73/v4/devices/16: Error: Request failed: 404
    at responseError (/home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:20:17)
    at Request._callback (/home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:114:21)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  statusCode: 404
}

Can you help?

**Comment by bombadiltom** [comment]
Please switch on debugging and provide more logs.
And is there a device with did 16 in:
http://192.168.178.73/v4/devices

**Comment by clipse2004** [comment]
i thougt my sensor is broken, and bought another one but same error now it is on devices/21. What is "no position in blind object"? What did this means? When i activate debug, where are the log files? i cannot find the logs
Big thanks for your help!

29.7.2020, 17:06:45 [HomePilot] Found environment sensor: Umweltsensor -  [21]29.7.2020, 17:06:45 [HomePilot] no position in blind object {
  description: '',
  deviceGroup: 3,
  did: 21,
  automations: [ 30, 50, 60, 100, 20, 40, [length]: 6 ],
  readings: {
    sun_detected: false,
    sun_brightness: 66000,
    sun_direction: 255,
    sun_elevation: 37,
    wind_speed: 0,
    rain_detected: false,
    temperature_primary: 32.7
  },
  timestamp: 1596035123,
  iconSetInverted: 0,
  iconSet: { k: 'iconset25' },
  name: 'Umweltsensor',
  statusValid: true,
  deviceNumber: 'XYXXX',
  uid: 'XXXXX',
  visible: true
}

**Comment by clipse2004** [comment]
hab gesehen du bist deutscher =) durch diesen Fehler gibt dann meine Homebridge den Geist auf :$

**Comment by bombadiltom** [comment]
bitte mal die Ausgabe von http://192.168.178.73/v4/devices schicken. Der Umweltsensor kann auch Rolladen steuern, deswegen "no position in blind object". Im Sourcecode ist die Klasse des Umweltsensors von der Klasse für Rolladen abgeleitet. Vielleicht hast du ein neueres Modell, bei welchem das nicht mehr so ist? Welche Devicenumber hat das Ding denn? Das ist die Artikelnummer, also nicht Geheimes.

**Comment by clipse2004** [comment]
Hello, naja das Teil hab ich vorgestern bekommen :) Die Artikelnummer lautet 3200 00 64 und die Ausgabe von deinem Link:
Ich danke Dir!

{"response":"get_visible_devices","devices":[{"description":"","deviceGroup":2,"did":1,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset8"},"messages":[],"name":"Rollo Schlafzimmer","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":52},"visible":true,"deviceNumber":"14234511","uid":"40dee1_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"","deviceGroup":2,"did":2,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset8"},"messages":[],"name":"Rollo Terrassentür","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"14234511","uid":"404562_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"","deviceGroup":2,"did":3,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rollo Wohnzimmer","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"14234511","uid":"40d9c3_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"","deviceGroup":2,"did":4,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rollo Küche","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":0,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":65},"visible":true,"deviceNumber":"14234511","uid":"404517_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"","deviceGroup":2,"did":20,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset7"},"messages":[],"name":"Markise","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"32000064_A","uid":"6920be_A_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"","deviceGroup":2,"did":7,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset8"},"messages":[],"name":"Rollo Essz. groß","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"14234511","uid":"404188_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"","deviceGroup":2,"did":9,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rollo Essz. klein","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":0,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":65},"visible":true,"deviceNumber":"14234511","uid":"404e05_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"","deviceGroup":2,"did":11,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rollo Badezimmer","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":0,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":65},"visible":false,"deviceNumber":"14234511","uid":"404093_1","voiceControlledBy":"","origin":"HomePilot"}]}

**Comment by bombadiltom** [comment]
da ist der Sensor ja auch gar nicht bei, ist der auf unsichtbar gestellt? 
Bei http://192.168.178.73/v4/devices?devtype=Sensor dürfte er aber enthalten sein, sonst würde er ihn nicht finden.
Halte ich für einen Fehler der API vom HomePilot, Workaround wäre dann, den Umweltsensor sichtbar zu machen

**Comment by clipse2004** [comment]
Ich hab die Geräte jetzt mal sortiert, du hast recht der taucht in den Devices überhaupt nicht auf. Ich verstehs nicht, bei anderen funktioniert das doch komischerweise auch :/ Kann ich bei der Anmeldung irgendwas falsch gemacht haben? Wenn ich auf deinen Link klicke kommt folgende Ausgabe: (Also Werte kriege ich definitiv und wird im HomePilot auch angezeigt also auf der Standartoberfläche)
{"response":"get_meters","meters":[{"description":"","deviceGroup":3,"did":21,"automations":[30,50,60,100,20,40],"readings":{"sun_detected":true,"sun_brightness":78000,"sun_direction":136.5,"sun_elevation":53,"wind_speed":0.0,"rain_detected":false,"temperature_primary":35.2},"timestamp":1596188403,"iconSetInverted":0,"iconSet":{"k":"iconset25"},"name":"Umweltsensor","statusValid":true,"deviceNumber":"32000064_S","uid":"6920be_S_1","visible":true}]}

**Comment by bombadiltom** [comment]
{"response":"get_visible_devices","devices" deutet darauf hin, dass hier nur sichtbare Geräte enthalten sind, weiß ich aber nicht genau, da ich nur sichtbare Geräte habe.

In der UI des Homepilot kann man umstellen: "Sichtbarkeit: Schaltet das Gerät sichtbar/unsichtbar" unter Konfiguration/Allgemein

**Comment by clipse2004** [comment]
yup das hatte ich gemacht, hab den HomePiloten grad auch mal neu gestartet aber das gleiche Ergebnis:
Der zeigt mir nur den Aktor "Markise" ,welcher ja vom Umweltsensor, stammt an. 
Ich hab keine Ahnung was ich noch tun kann damit der endlich in dieser Device Liste auftaucht :/

{"response":"get_visible_devices","devices":[
{"description":"","deviceGroup":2,"did":1,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset8"},"messages":[],"name":"Rollo Schlafzimmer","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"14234511","uid":"40dee1_1","voiceControlledBy":"","origin":"HomePilot"},
{"description":"","deviceGroup":2,"did":2,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset8"},"messages":[],"name":"Rollo Terrassentür","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"14234511","uid":"404562_1","voiceControlledBy":"","origin":"HomePilot"},
{"description":"","deviceGroup":2,"did":3,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rollo Wohnzimmer","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"14234511","uid":"40d9c3_1","voiceControlledBy":"","origin":"HomePilot"},
{"description":"","deviceGroup":2,"did":4,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rollo Küche","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"14234511","uid":"404517_1","voiceControlledBy":"","origin":"HomePilot"},
{"description":"","deviceGroup":2,"did":20,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset7"},"messages":[],"name":"Markise","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"32000064_A","uid":"6920be_A_1","voiceControlledBy":"","origin":"HomePilot"},
{"description":"","deviceGroup":2,"did":7,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset8"},"messages":[],"name":"Rollo Essz. groß","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"14234511","uid":"404188_1","voiceControlledBy":"","origin":"HomePilot"},
{"description":"","deviceGroup":2,"did":9,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rollo Essz. klein","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"14234511","uid":"404e05_1","voiceControlledBy":"","origin":"HomePilot"},
{"description":"","deviceGroup":2,"did":11,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Rollo Badezimmer","properties":{"closingContact":3,"dawn":2,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"14234511","uid":"404093_1","voiceControlledBy":"","origin":"HomePilot"}]}

**Comment by clipse2004** [comment]
Was meinst du soll ich später den HomePilot mal komplett zurücksetzen? Ich hatte vorher einen Umweltsensor mit Softwarestand 0.1.1 welchen ich versucht habe mit dem HomePilot zu steuern, der war aber dafür zu alt. Meinst das könnte den Fehler verursachen?

**Comment by bombadiltom** [comment]
Ne, das wird nichts bringen, der Umweltsensor ist ein Sonderfall, da er gleichzeitig Sensor und Aktor ist, anscheinend ist das das Problem. Problem für mich ist, dass ich keinen habe und die Implementierung jemand anders gemacht hat.
Sieht so aus, als ob er als Sensor eingebunden wird und dann versucht wird mit der DID des Sensors die Rolladen zu steuern, was nicht funktionieren kann. Eigentlich müsste man die getrennt einbinden.

Welche Devicenumbers werden denn da jetzt geliefert?

32000064_A unter http://192.168.178.73/v4/devices für die Markise
32000064 unter http://192.168.178.73/v4/devices?devtype=Sensor ?
oder auch 32000064_S

**Comment by clipse2004** [comment]
Richtig für die Markise kommt 
"deviceNumber":"32000064_A"
und bei dem Umweltsensor (zweiter Link):
"deviceNumber":"32000064_S"
also einmal A und einmal S, ich würde dir gerne helfen aber scripten kann ich net :/

**Comment by bombadiltom** [comment]
Mal zurück zum eigentlichen Problem: stürzt denn Homebridge komplett ab? Sollte eigentlich nicht passieren, auch wenn die genannten Fehler auftreten.

**Comment by bombadiltom** [comment]
probier mal bitte 0.4.10

**Comment by clipse2004** [comment]
> Mal zurück zum eigentlichen Problem: stürzt denn Homebridge komplett ab? Sollte eigentlich nicht passieren, auch wenn die genannten Fehler auftreten.

Naja die Geräte werden als „nicht erreichbar“ angezeigt und Homebridge versucht immer wieder zu verbinden. Erst wenn ich den Umweltsensor in einen anderen Raum packe wo i h gerade nicht zugreife geht es wieder.

Ps: ist noch mit der älteren Version die neue ist immer noch nicht live

**Comment by bombadiltom** [comment]
live ist sie seit drei Stunden:
https://www.npmjs.com/package/homebridge-rademacher-homepilot

**Comment by clipse2004** [comment]
I see :) Grad die Sachen die man braucht dauern immer länger ^^ 
Ich melde mich sobald ich es installiert habe.

**Comment by clipse2004** [comment]
Also ich seh’s immer noch nicht. :/

**Comment by bombadiltom** [comment]
npm install -g homebridge-rademacher-homepilot@0.4.10

**Comment by clipse2004** [comment]
> npm install -g homebridge-rademacher-homepilot@0.4.10

So einfach ist das bei Hoobs nicht

**Comment by bombadiltom** [comment]
müsste aber gehen, intern macht der doch auch nichts anderes, aktualisiert nur seine Daten zu selten...

**Comment by clipse2004** [comment]
> müsste aber gehen, intern macht der doch auch nichts anderes, aktualisiert nur seine Daten zu selten...

Hab ich schon mal versucht aber da gibt es bisschen was zu beachten, zB nicht global also -g etc.
Hab denen aber schon geschrieben

**Comment by clipse2004** [comment]
So konnte grad das Update einspielen, läuft alles wieder einwandfrei :) Sag mal im Umweltsensor wird die Markise ein zweites mal angezeigt. Also einmal als Markise und einmal im Umweltsensor, wird wahrscheinlich nicht anders gehen oder? 
Ich danke dir vielmals für deine Hilfe!
