### ISSUE TITLE
@0.4.10 ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by ms29092** [bombadiltom/homebridge-rademacher-homepilot#57]
Hallo bombadiltom,
habe dein PlugIn wieder aktiviert, nachdem die Homebridge von einem PC auf ein rasberry pi mit Hoobs umgezogen ist. Irgendwie war Homebridge nicht stabil auf dem PC sobald das PlugIn von die gelaufen ist...alle Geräte keine Antwort....da habe ich das RademacherBlinds PlugIn benutzt.

Was jetzt auf dem Rasberry häufig kommt ist die folgende Meldung...für alle Geräte im HomePilot (14 Geräte vorhanden). 
Kann diese kommen, da ich aktuell noch das Rademacher Blinds parallel nutze ?.
Den Umweltsensor habe ich auch als Gerät, da wäre ein "Nice to have" wenn der Regensensor ausgewertet würde.

Wenn du weitere Info´s brauchst, oder Logs einfach Bescheid geben.

4.8.2020, 16:55:35 [RademacherHomePilot] GET error for path http://192.168.55.195/v4/devices?devtype=Sensor: Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:416:28)
    at ClientRequest.emit (events.js:310:20)
    at Socket.emitRequestTimeout (_http_client.js:709:9)
    at Object.onceWrapper (events.js:416:28)
    at Socket.emit (events.js:322:22)
    at Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}

Grüße
Marcus

**Comment by bombadiltom** [comment]
das sind Netzwerkprobleme, mögliche Ursachen sind ein langsames Netz, ein überlasteter Pi oder ein überlasteter Homepilot.
Ich habe bei mir bei vielen Geräten "Im Status anzeigen" ausgeschaltet, das führt nämlich bei Aufrufe der Home App dazu, dass zu jedem Gerät ein GET abgesetzt wird, um den Status zu ermitteln, wenn das aus ist, erfolgt das nur, wenn das entsprechende Gerät auch angezeigt wird, z.B. wenn man auf den Raum wechselt
