### ISSUE TITLE
Frage „inverted“ ?

### ISSUE THREAD

**Issue by clipse2004** [bombadiltom/homebridge-rademacher-homepilot#59]
Hi,
Du eine Frage ist es möglich die Funktion „inverted“ mit einzubauen, damit das im HomeKit genauso wie in der HomePilot App dargestellt wird?

**Comment by bombadiltom** [comment]
"inverted" wird berücksichtigt, indem 100-position gerechnet wird, so weit ich weiß, kann Homekit das nicht anders
