### ISSUE TITLE
Support "Treppenhausfunktion"

### ISSUE THREAD

**Issue by bombadiltom** [bombadiltom/homebridge-rademacher-homepilot#6]
Ich hab jetzt nur ein kleines Problem, nutze ich die Treppenhaus Funktion im Homepilot, so dass der Aktor nach einer vorgegebenen zeit wieder ausschaltet, wird er Seitens Siri immer noch als eingeschaltet angezeigt.

**Comment by sg70** [comment]
Ich denke, Homebridge sollte regelmäßig den Status abfragen. Ähnlich wie [homebridge-fritz](https://github.com/andig/homebridge-fritz)
