### ISSUE TITLE
Start2smart support?

### ISSUE THREAD

**Issue by bojomojo** [bombadiltom/homebridge-rademacher-homepilot#62]
Does this also support the start2smart rademacher bridge?
It uses the same gurtwickler that is also used with homepilot but its much cheaper

https://www.rademacher.de/smart-home/produkte/start2smart

**Comment by bombadiltom** [comment]
yes, seems to use the same API, another user reported it as working

**Comment by bojomojo** [comment]
Can you point me where that is mentioned? To check for more setails

Sent from my iPhone

On 4. Nov 2020, at 09:08, Tom Lorenz <notifications@github.com> wrote:

﻿

yes, seems to use the same API, another user reported it as working

**Comment by bombadiltom** [comment]
sorry, this was done via email

**Comment by bojomojo** [comment]
Confirmed working. 
Exactly same steps as the homepilot.
