### ISSUE TITLE
Can homekit display up to date status?

### ISSUE THREAD

**Issue by bojomojo** [bombadiltom/homebridge-rademacher-homepilot#63]
Can homeKit display correct up to date status (opened/closed/percentage) even if the keys were directly used on the Gurtwickler to open/close)?

And in case of manual control (directly from the belt)

**Comment by bombadiltom** [comment]
The accessory has to poll the status which is not implemented for blinds by now.
I can add it.

**Comment by bojomojo** [comment]
That would be awesome. Because otherwise things get messy if someone uses the buttons to open/close partially, and then you ask Siri to open to 50% for example. I assume it wont work in that case unless homekit already knows where the blinds are. 

When can we expect such a feature?

**Comment by bombadiltom** [comment]
50% would work as every position is an absolute value between 0 and 100, there is no relative movement.
as a workaround just ask Siri twice ;-)
Don't know when I will find the time for it, just watch this issue...

**Comment by bojomojo** [comment]
Do we know the API to poll the status already? I looned around broefly but only found the up/down/goto apis

Sent from my iPhone

On 6. Nov 2020, at 08:36, Tom Lorenz <notifications@github.com> wrote:

﻿

50% would work as every position is an absolute value between 0 and 100, there is no relative movement.
as a workaround just ask Siri twice ;-)
Don't know when I will find the time for it, just watch this issue...

**Comment by bombadiltom** [comment]
fixed in 0.5.0

**Comment by bojomojo** [comment]
Confirmed working! Thanks
