### ISSUE TITLE
Blinds showing “No response for 10seconds or so”

### ISSUE THREAD

**Issue by bojomojo** [bombadiltom/homebridge-rademacher-homepilot#64]
When I open the home app after a while, the blinds show “no response” for a couple of seconds. Then it updates correctly. Is this normal?

**Comment by bojomojo** [comment]
I am now in a state thats its showing No Response for like 1 min. Then it updated 
Every other accessory was working during this 1 min
Accessing homebridge via webinterface also worked. 

I have a mesh master and 2 mesh repeaters, could it be an issue?

**Comment by bombadiltom** [comment]
Maybe switch off "Show in status" (don't know if this the exact translation) for all devices and remove as many as possible from your favorites. Anyway, this is not a problem I can fix with the plugin
