### ISSUE TITLE
Bei Rolläden highlighten, wenn sie geschlossen sind und nicht, wenn sie geöffnet sind?

### ISSUE THREAD

**Issue by emufan** [bombadiltom/homebridge-rademacher-homepilot#65]
Vorab: Tolles Plug-In. Funktioniert tadellos.

Nur sind die Geschmäcker ja verschieden.

a. Bei Rolläden highlighten, wenn sie geschlossen sind und nicht, wenn sie geöffnet sind? Die Home App stellt es aktiv/hell/besonders dar, wenn der Rolladen geöffnet ist (quasi Lampe an). Das ist für mich aber der Standard und ich hätte gern, dass aktiv/hell/besonders dargestellt wird, wenn ein Rolladen noch geschlossen ist. Im Code habe ich aber noch nicht gefunden, wie ich das ändern kann.

Mit inverted passt es quasi, aber dann sagt der Text auch das Gegenteil, d.h. geschlossen wird als aktiv/hell/besonders/"Lampe an" angezeigt - wie gewünscht - nur dann ist der Text halt "geöffnet", was nicht stimmt.

b. Auch zeigt Home/Eve, usw. bei geöffnetem Rolladen 100% an, Homeplilot aber 0%. Es geht also davon aus 0% geschlossen. Home aber von 100% geöffnet. Kann man das im Code umstellen, sodass es synchron ist?

Ich möchte also zusammengefasst mit beiden Fragen (wenngleich mit a. wichtiger wäre als b oder a+b ;-)). Darstellung/Ansteuerung: Wenn geöffnet 0% und ausgegraut dargestellt und wenn geschlossen 100% und aktiv/hell/besonders.

Ginge dies und ich habe nur die betreffenden Stellen bisher nicht gefunden? Vielen Dank im Voraus.

**Comment by bombadiltom** [comment]
wüsste nicht, wie man das ändern könnte, laut Doku ist 0 geschlossen und 100 offen:
https://developer.apple.com/documentation/homekit/hmcharacteristictypecurrentposition

**Comment by emufan** [comment]
Schade aber meinetwegen aber auch o.k.

Aber kann man die Anzeige definieren? 0 geschlossen = "Lampe an" und 100 offen als "Lampe aus"? Statt wie aktuell anders herum?

**Comment by bombadiltom** [comment]
Da müsste man sich bei Apple beschweren

**Comment by emufan** [comment]
Ich will mich ja nicht beschweren, sondern meine Frage war ob man das per PlugIn-Proxy-Code "umdrehen" kann?`Quasi mitgeben, was der Highlight-Zustand ist oder was die Beschreibung.

**Comment by bombadiltom** [comment]
nein, man gibt nur einen Wert zwischen 0 und 100 an
