### ISSUE TITLE
Blind showing as continuously closing regardless of the actual state. 

### ISSUE THREAD

**Issue by bojomojo** [bombadiltom/homebridge-rademacher-homepilot#66]
After the hassle of hb not bolting because of the ui-x plugin update today, and working around it by restoring an old version. One of my blinds shows continuosuly „closing“ and if I clcik on it, it says open. If I try to close, it goes back to „closing“. 
Note: the blinds are actually closed. Operating them from the homepilot app works fine. 

How can I get you proper logs to check this?

**Comment by bojomojo** [comment]
The problem is with the homepilot password.
I set a password recently to the device. 
Eventhough I tried adding the password in the configuration, it doesnt seem to work. 
Note:I am using the smart2start bridge

**Comment by bombadiltom** [comment]
password_hashed gesetzt?

**Comment by bojomojo** [comment]
es hat sich nach einem restart gelöst

Best Regards,
Shadi


________________________________
