### ISSUE TITLE
Szenen wieder aus HomeKit löschen lassen?

### ISSUE THREAD

**Issue by fritte87** [bombadiltom/homebridge-rademacher-homepilot#67]
Hi,
hab beim Homepilot meine Auslöser sowie Szenen geändert und welche gelöscht...
Die Szenen bleiben jedoch in meiner Homekit komplett drin...
gibts ne Möglichkeit diese komplett verschwinden zu lassen und neu einzulesen?

Die cachesAccessories Datei habe ich schon gelöscht, bringt jedoch keine Abhilfe...

Danke

**Comment by bombadiltom** [comment]
gerade erfolgreich getestet:

- Szene löschen
- homebridge beenden
- cachedAccesories löschen
- homebridge starten

dann ist die Szene aus Homekit verschwunden, wichtig ist, die Datei nicht bei laufendem Homebridge zu löschen, denn beim Beenden wird sie vermutlich noch einmal erzeugt
