### ISSUE TITLE
Missing Option to disable devices

### ISSUE THREAD

**Issue by DerKarussellbremser** [bombadiltom/homebridge-rademacher-homepilot#68]
Hi there,

may it be possible to add an option to include or exclude devices from beeing transfered to Homekit?
I have a lot of devices i don't want in Homekit and i can't get them out.

Thanks a lot, keep up the great work!

br .. Robin

**Comment by bombadiltom** [comment]
if you set them invisible in HomePilot, they should not appear in Homekit also.

**Comment by DerKarussellbremser** [comment]
Allready tested that switch. For a Test i now disabled all Rademacher Devices, 1h ago.. All still there. Cleared cache and begun from start.. i can’t hide anything.
![B3559B8A-8616-4D4E-9669-C824EE8C7906](https://user-images.githubusercontent.com/67138735/100525506-b6c8e380-31c1-11eb-882a-610b6ee4a620.png)
![5EF484BE-859B-4FD3-81BE-B87EC5F7008E](https://user-images.githubusercontent.com/67138735/100525513-bcbec480-31c1-11eb-9d1f-22057bfe384b.png)

**Comment by DerKarussellbremser** [comment]
HomePilot, i twistest Names! Sorry, to many „Home“ around ne.
I can’t Switch them to invisible in HomePilot, i need them in the Rademacher App.

**Comment by DerKarussellbremser** [comment]
Nevertheless, i testet it to switch them invisible in HomePilot. Also not working, even after waiting time and cachereset

**Comment by DerKarussellbremser** [comment]
I managed it to just include devices i want with the data.did. a little „if data.did == „the ids i needed““ in some places and all was nice. Thanks

**Comment by DerKarussellbremser** [comment]
Status Log:
[30/11/2020, 19:13:35] [RademacherHomePilot] switch is online: Kompressor [1010018]
[30/11/2020, 19:13:35] [RademacherHomePilot] Not matching DID: 1010017

The second Message is from my Change .. i can choose the DIDs i need .. maybe an idea to implement to your plugin.

**Comment by clipse2004** [comment]
Wie kann ich dieses DIDs herausfinden? Ist das die Seriennummer? Bei mir wird nämlich im HomeKit Screen nix mit DID angezeigt

**Comment by DerKarussellbremser** [comment]
In den Bereich „did_list“ eine Fake-did eintragen, 7-Stellig, 9999999 zB , das Paramater „did_list_usage“ da drüber auf „include“ oder „exclude“ und du solltest alle Dids der Geräte im Status beim Reboot sehen.
Aber Vorsicht: Ich gehe fest davon aus das dann deine Zuordnung der Geräte in HomeKit verloren geht!

did_list: enter the Device IDs (DIDs) you want to be shown in HomeKit. You can find them in the Status Screen of HomeBridge if you enable "did_list_usage" and insert at least one fake DID Example: "did_list": [1010101,1010102,1010133]

**Comment by DerKarussellbremser** [comment]
Es wäre möglich wenn du „exclude“ benutzt und eine Fake einträgst das dann nichts aus HomeKit raus fliegt ... aber ohne Gewähr

**Comment by clipse2004** [comment]
Hab ich versucht mit folgendem:

            "did_list_usage": "exclude",
            "did_list": [
                1010101,
                1010102,
                1010133
            ]
        }

Keine Chance der zeigt mir einfach nix an :/ würde gerne den zweiten Aktor exkludieren

**Comment by bombadiltom** [comment]
http://homepilot/v4/devices => da steht dann die did für jedes Device, 
müssten immer bei 10000 anfangen

**Comment by bombadiltom** [comment]
ansonsten debug auf true, da werden dann meine ich auch alle ausgeben

**Comment by bombadiltom** [comment]
steht auch so im Log in eckigen Klammern beim Start:

[12/6/2020, 5:40:36 PM] [RademacherHomePilot] did filtering: excluding did 10037
[12/6/2020, 5:40:36 PM] [RademacherHomePilot] blinds are online: bodentief [10000]

**Comment by clipse2004** [comment]
Leider nein mein log zeigt immer das gleiche auch mit debug:

[RademacherHomePilot] Successfully logged into HomePilot.
[6.12.2020, 20:32:08] [RademacherHomePilot] Found environment sensor: Wettersensor -  [26]
[6.12.2020, 20:32:08] [RademacherHomePilot] Added environment sensor: Wettersensor -  [26]
[6.12.2020, 20:32:08] [RademacherHomePilot] blinds are online: Rollo Schlafzimmer [1]
[6.12.2020, 20:32:08] [RademacherHomePilot] blinds are online: Rollo Terrassentür [2]
[6.12.2020, 20:32:08] [RademacherHomePilot] blinds are online: Rollo Wohnzimmer [3]
[6.12.2020, 20:32:08] [RademacherHomePilot] blinds are online: Rollo Küche [4]
[6.12.2020, 20:32:08] [RademacherHomePilot] blinds are online: großer Rollo Esszimmer [7]
[6.12.2020, 20:32:08] [RademacherHomePilot] blinds are online: kleiner Rollo Esszimmer [9]
[6.12.2020, 20:32:08] [RademacherHomePilot] blinds are online: Aktor Markise [25]
[6.12.2020, 20:32:08] [RademacherHomePilot] blinds are online: Rollo Badezimmer [11]

bei dir steht hinter Bodentief eine 100000, bei mir nur 2 Stellen. :/
Mit Debug True wirft der mir auch nix anders aus. 
HomePilot/v4/devices -> unauthoriziert mit HomePilot/devices komme ich auf die Oberfläche, dort sind jetzt allerdings nicht nur meine Geräte aufgelistet 😂
Ich sag dir der HomePilot macht mich noch fertig 😂😂

**Comment by bombadiltom** [comment]
das sind dann die dids, nimm einfach die, anscheinend beginnen sie bei dir bei 1, bei mir bei 10000 bei anderen bei 100000, keine Ahnung was das soll

**Comment by clipse2004** [comment]
Achsooo und ich dachte die sind immer so 9 Stellung ^^ ja jetzt hat es funktioniert.
Ich danke euch
