### ISSUE TITLE
Troll Basis DuoFern

### ISSUE THREAD

**Issue by aflint99** [bombadiltom/homebridge-rademacher-homepilot#7]
Hi

das homebridge-log erzeugt bei mir folgende Ausgabe: Unknown product: Troll Basis DuoFern
Gibt es eine Chance, diese Aktoren in das plugin einzubinden ?

**Comment by bombadiltom** [comment]
Hi,

was ist denn das?

Best mobile regards,

Tom Lorenz

**Comment by aflint99** [comment]
das sind Autoren, mit denen man Rohrmotoren steuern kann. Die Funktionalität ist genau die selbe wie bei den Rollotron Gurtwicklern.

**Comment by aflint99** [comment]
problem gelöst: 
ich habe die Index.js ein wenig modifiziert.

Original:
// blinds
                    if(data.productName.includes("RolloTron") || data.productName.includes("Troll Comfort") ||
                       data.productName.includes("Rohrmotor") || data.productName.includes("Connect-Aktor") ||
                       data.productName.includes("RolloTube"))

habe ich so geändert:
// blinds
                    if(data.productName.includes("RolloTron") || data.productName.includes("Troll Comfort") ||
                       data.productName.includes("Rohrmotor") || data.productName.includes("Connect-Aktor") ||
                       data.productName.includes("RolloTube") ||  data.productName.includes("Troll Basis"))

jetzt funktioniert es ;-)
Danke für das coole plugin

**Comment by bombadiltom** [comment]
Ggf. gibt es noch weitere Varianten von „Troll“, habe es mal so eingetragen in der soeben veröffentlichten Version 0.0.6:

// blinds
if(data.productName.includes("RolloTron") || data.productName.includes("Troll ") ||
   data.productName.includes("Rohrmotor") || data.productName.includes("Connect-Aktor") ||
   data.productName.includes("RolloTube"))
{

MfG,

Tom Lorenz
Im Grünen Winkel 21
59423 Unna
Tel: 02303 592524
Fax: 02303 592534
mailto:tom@lorenz-unna.de

**Comment by aflint99** [comment]
Super

Vielen Dank
