### ISSUE TITLE
Fensterkontakte „gekippt“

### ISSUE THREAD

**Issue by consi51** [bombadiltom/homebridge-rademacher-homepilot#72]
Hallo, erst einmal vielen Dank. Erfreue mich wirklich an dem tollen Plugin.

Gibt es eine Möglichkeit, das ich die fensterkontakte im Modus "gekippt" in HomeKit erkennen kann? 

Sie werden weiterhin als geschlossen dargestellt. Lieber wäre mir als geöffnet, falls gekippt seitens HomeKit nicht möglich ist.
Viele Grüße

**Comment by bombadiltom** [comment]
Ist im Moment als HomeKit ContactSensor implementiert, also gibt es nur Kontakt ja/nein

Was steht denn bei dem Device unter readings.contact_state bei gekipptem Fenster?
http://homepilot/v4/devices?devtype=Sensor

**Comment by consi51** [comment]
Du meinst sicher, wenn das Fenster gekippt ist:

Dann steht da tilted

Schlafzimmer","deviceGroup":3,"did":1010124,"automations":[120],"readings":{"contact_state":"tilted"},"batteryStatus":98,"batteryLow":false,"timestamp":1608055746,"iconSetInverted":0,"iconSet":{"k":"iconset12"},"name":"TÃ¼rkontakt Schlafzimmer","statusValid":true,"deviceNumber":"32003164","uid":"ac2ee0_1","visible":true},{"description":"Dachboden","deviceGroup":3,"did":1010122,"automations":[120],"readings":{"contact_state":"closed"},"batteryStatus":100,"batteryLow":false,"timestamp":1607954865,"iconSetInverted":0,"iconSet":

**Comment by consi51** [comment]
Klappt. Vielen Dank für die Hilfe 👍
