### ISSUE TITLE
The actor within the 9494-2 (rademacher product code) is not supported.

### ISSUE THREAD

**Issue by michaelkelch** [bombadiltom/homebridge-rademacher-homepilot#76]
The actor within the 9494-2 (rademacher product code) is not supported.

I can't find "32501972" to be processed index.js 

Yes, this HW-device is on the one hand a "remote control" and this part must not be supported, but the build in actor should be supported as we need this element in Home available

If you have any questions, please let me know..

cheers Michael

**Comment by michaelkelch** [comment]
Perfect, this was quick, I will test today!

 

Von: Tom Lorenz <notifications@github.com>
Antworten an: bombadiltom/homebridge-rademacher-homepilot <reply@reply.github.com>
Datum: Sonntag, 31. Januar 2021 um 11:32
An: bombadiltom/homebridge-rademacher-homepilot <homebridge-rademacher-homepilot@noreply.github.com>
Cc: Michael Kelch <michael.kelch@t-online.de>, Author <author@noreply.github.com>
Betreff: Re: [bombadiltom/homebridge-rademacher-homepilot] The actor within the 9494-2 (rademacher product code) is not supported. (#76)

 

Closed #76 via 037d404.

**Comment by bombadiltom** [comment]
and I ordered two of them, did not know they exist, thanks ;-)

**Comment by michaelkelch** [comment]
I tested #76 solution, no yet successfull - question:  why integration of 9494-2 as blind; shouldn't it be seen as a switch, just "on or off" ..

**Comment by bombadiltom** [comment]
makes sense

**Comment by michaelkelch** [comment]
now tested again and ..  :-) .. it works fine:
example of the status of one of my "32501972_A"

Danke !!

{
      "description": "Wohnzimmer Decke",
      "deviceGroup": 1,
      "did": 1010053,
      "hasErrors": 0,
      "iconSetInverted": 0,
      "iconSet": { "k": "iconset4" },
      "messages": [],
      "name": "EG 15 Wohnzimmer Deckenlampe",
      "properties": {
        "closingContact": 3,
        "dawn": 3,
        "dusk": 3,
        "motion": 3,
        "rain": 3,
        "smartphone": 3,
        "smoke": 3,
        "sun": 3,
        "temperature": 3,
        "time": 2,
        "trigger": 3,
        "warning": 3,
        "wind": 3
      },
      "statusValid": true,
      "statusesMap": { "Manuellbetrieb": 0, "Position": 0 },
      "visible": true,
      "deviceNumber": "32501972_A",
      "uid": "740c5a_A_1",
      "voiceControlledBy": "",
      "origin": "HomePilot"
    },

**Comment by martak101** [comment]
Hello @all

 

Here it works too.

 

Great job again

 

Von: michael kelch <notifications@github.com>
Antworten an: bombadiltom/homebridge-rademacher-homepilot <reply@reply.github.com>
Datum: Montag, 1. Februar 2021 um 15:38
An: bombadiltom/homebridge-rademacher-homepilot <homebridge-rademacher-homepilot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [bombadiltom/homebridge-rademacher-homepilot] The actor within the 9494-2 (rademacher product code) is not supported. (#76)

 

now tested again and .. :-) .. it works fine:
example of the status of one of my "32501972_A"

Danke !!

{
"description": "Wohnzimmer Decke",
"deviceGroup": 1,
"did": 1010053,
"hasErrors": 0,
"iconSetInverted": 0,
"iconSet": { "k": "iconset4" },
"messages": [],
"name": "EG 15 Wohnzimmer Deckenlampe",
"properties": {
"closingContact": 3,
"dawn": 3,
"dusk": 3,
"motion": 3,
"rain": 3,
"smartphone": 3,
"smoke": 3,
"sun": 3,
"temperature": 3,
"time": 2,
"trigger": 3,
"warning": 3,
"wind": 3
},
"statusValid": true,
"statusesMap": { "Manuellbetrieb": 0, "Position": 0 },
"visible": true,
"deviceNumber": "32501972_A",
"uid": "740c5a_A_1",
"voiceControlledBy": "",
"origin": "HomePilot"
},
