### ISSUE TITLE
9494-2

### ISSUE THREAD

**Issue by martak101** [bombadiltom/homebridge-rademacher-homepilot#77]
Hallo Tom,

mit issue #76 hast Du o.g. Mehrfachtaster integriert. Vielen Dank soweit.
Aber:
nach dem Update des Plugin auf 0.6.6 bekomme ich weiterhin ein Unknown Product.
Bei mir meldet sich das fragliche Device mit 32501972_A

Kann es an dem _A liegen?

**Comment by bombadiltom** [comment]
ja, das ist vermutlich der Taster selbst, für den gibt es keine Lösung im Plugin
