### ISSUE TITLE
Bewegungsmelder wird im Terminal angezeigt aber nicht im Homekit

### ISSUE THREAD

**Issue by thimof** [bombadiltom/homebridge-rademacher-homepilot#79]
![Screenshot 2021-02-08 101830](https://user-images.githubusercontent.com/78726872/107199689-0401d680-69f7-11eb-8bff-66fe728c26c8.png)
Ich habe ein Update des Plugins gemacht und gesehen, dass mir der Dimmer angezeigt wird. Habe dann die did_usage_list auf include gesetzt und die did des gefundenen Melders eingegeben. Leider wird mir dieser nun nicht im Homekit angezeigt. Ist das ein Fehler, oder wird der einfach noch nicht unterstützt?

**Comment by bombadiltom** [comment]
Bewegungsmelder kann das Plugin noch nicht

**Comment by bombadiltom** [comment]
duplicate of #48
