### ISSUE TITLE
2 Kanal Schaltaktor

### ISSUE THREAD

**Issue by aflint99** [bombadiltom/homebridge-rademacher-homepilot#8]
wenn ich einen 2-Kanal Schaltaktor im Homepilot einbinde, erhalte ich folgenden Fehler:

/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSwitchAccessory.js:50
        body.devices.forEach(function(data) {
                     ^
homebridge.service: Main process exited, code=exited, status=1/FAILURE
homebridge.service: Unit entered failed state.
homebridge.service: Failed with result 'exit-code'.
pam_unix(sudo:session): session closed for user root
homebridge.service: Service hold-off time over, scheduling restart.

Die Homebridge startet dann permanent neu, sobald getCurrentState aufgerufen wird.
Wenn ich nur einen Kanal des Autors in den Homepilot einbinde, funktioniert es.

**Comment by aflint99** [comment]
anscheinend kann folgendes passieren.
Im JSON, das zurückgegeben wird, könnte ein Duplikat der selben Instanz erzeugt werden (darauf hin stürzt die Homebridge ab), daher habe ich in RademacherSwitchAccessory.js 
diese Änderung gemacht (in der Hoffnung dass devices.did tatsächlich KEIN Duplikat sein kann ;-)

RademacherSwitchAccessory.prototype.getCurrentState = function(callback) {
    this.log("%s - Getting current state for %s", this.accessory.displayName, this.accessory.UUID);

    var self = this;
    var serial = this.sw.serial;
    var name = this.sw.name;
    **var did = this.sw.did;**
    request.get({
        timeout: 1500,
        strictSSL: false,
        url: this.url + "/deviceajax.do?devices=1"
    }, function(e,r,b) {
        if(e) return callback(new Error("Request failed: "+e), false);
        var body = JSON.parse(b);

        body.devices.forEach(function(data) {
            if(**data.did==did** && data.serial == serial && data.name == name )
            {
                var pos = data.position;
                callback(null, (pos==100?true:false));
            }
        });

    });
};
--

ich habe folgendes JSON  beim Aufruf von /deviceajax.do?devices=1 erhalten
--
"devices": [
        {
            "did": 1010014,
            "name": "**DuoFern Universal-Aktor 2-Kanal**",
            "description": "Esszimmer",
            "initialized": 1,
            "position": 0,
            "productName": "DuoFern Universal-Aktor 2-Kanal",
            "serial": "**43 89 89**",
            "statusesMap": {
                "Position": 0,
                "Manuellbetrieb": 0
            },
            .....
 },
        {
            "did": 1010015,
            "name": "**DuoFern Universal-Aktor 2-Kanal**",
            "description": "Küche",
            "initialized": 1,
            "position": 100,
            "productName": "DuoFern Universal-Aktor 2-Kanal",
            "serial": "**43 89 89**",
            "statusesMap": {
                "Position": 100,
                "Manuellbetrieb": 0
            },....

**Comment by bombadiltom** [comment]
Moin,

macht Sinn, es hätte auch genügt, die unterschiedlich zu benennen:

"did": 10029,
"name": "Flursteckdose 2",
"description": "Flursteckdose 2",
"initialized": 1,
"position": 100,
"productName": "DuoFern Universal-Aktor 2-Kanal“,

Werde ich morgen mal in allen Accessories korrigieren...

MfG,

Tom Lorenz
Im Grünen Winkel 21
59423 Unna
Tel: 02303 592524
Fax: 02303 592534
mailto:tom@lorenz-unna.de

**Comment by bombadiltom** [comment]
Hmm, ich kann im Homepilot beides ändern, das JSON ist echt

Best mobile regards,

Tom Lorenz

**Comment by aflint99** [comment]
Wieder was gelernt. Danke für den Tip

**Comment by bombadiltom** [comment]
Hi nochmal,

an vielen anderen Stellen war das schon auf did alleine umgestellt, habe es in 0.0.7 angepasst.
Danke für den Hinweis.

MfG,

Tom Lorenz
Im Grünen Winkel 21
59423 Unna
Tel: 02303 592524
Fax: 02303 592534
mailto:tom@lorenz-unna.de
