### ISSUE TITLE
Problem mit Homebridge v1.3.0

### ISSUE THREAD

**Issue by kbromm** [bombadiltom/homebridge-rademacher-homepilot#83]
Alle meine Geräte sind nach dem Update auf Homebridge v1.3.0 verschwunden. 
Ein Downgrade auf Plugin v0.6.9 brachte Abhilfe.
Allerdings gibt es folgende Warnung:
[homebridge-rademacher-homepilot] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response! See https://git.io/JtMGR for more info.

**Comment by Boehmer86** [comment]
Hallo zusammen

Ich kann das Problem bestätigen. Ich arbeite noch auf 1.3 und hoffe auf einen baldigen Fix.

Hier der Debug Log Output:

> [2/21/2021, 9:39:21 PM] [homebridge-rademacher-homepilot] This plugin generated a warning from the characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response! See https://git.io/JtMGR for more info.

> [2/21/2021, 9:39:21 PM] [homebridge-rademacher-homepilot] Error: 
>     at Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2063:79)
>     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1618:22
>     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
>     at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherThermostatAccessory.js:83:20
>     at Request._callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:137:13)
>     at Request.self.callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:315:20)
>     at Request.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:315:20)
>     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:1076:12)


Viele Grüße

Robert

**Comment by danny1605** [comment]
For me exactly the same problem, the update to v 1.3.0

[homebridge-rademacher-homepilot] This plugin generated a warning from the characteristic 'Target Position': SET handler returned write response value, though the characteristic doesn't support write response! See https://git.io/JtMGR for more info.
