### ISSUE TITLE
Issue?? "write response"...?

### ISSUE THREAD

**Issue by luissimoes** [bombadiltom/homebridge-rademacher-homepilot#84]
I have this error now...

<<
[homebridge-rademacher-homepilot] This plugin generated a warning from the characteristic 'Target Position': SET handler returned write response value, though the characteristic doesn't support write response! See https://git.io/JtMGR for more info.
>>

sorry.. no idea what this means but am getting this

**Comment by FlasSh21** [comment]
I have the same issue

**Comment by Boehmer86** [comment]
This looks like a duplicate of #83 – to confirm, you all upgraded to Homebridge 1.3.x, correct?

Best

Robert

**Comment by luissimoes** [comment]
> This looks like a duplicate of #83 – to confirm, you all upgraded to Homebridge 1.3.x, correct?
> 
> Best
> 
> Robert

yep... I am on 1.3.0
