### ISSUE TITLE
Fehler Thermostate

### ISSUE THREAD

**Issue by martak101** [bombadiltom/homebridge-rademacher-homepilot#87]
Guten Morgen,
mit Version 0.7.3 werden die Thermostate nun zwar wieder erkannt. Beim Versuch, diese über Homekit anzusteuern, kommt es aber zu folgendem Fehler. Muss evtl. irgendetwas zusätzlich in der Config geändert werden?

24.2.2021, 04:40:11 [RademacherHomePilot] PUT error for path http://192.168.178.30/devices/1010011: ReferenceError: err is not defined
    at /home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherThermostatAccessory.js:90:9
    at /home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:122:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
24.2.2021, 04:40:11 (node:6150) UnhandledPromiseRejectionWarning: ReferenceError: err is not defined
24.2.2021, 04:40:11 at /home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherThermostatAccessory.js:90:9
24.2.2021, 04:40:11 at /home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:126:9
24.2.2021, 04:40:11 at runMicrotasks (<anonymous>)
24.2.2021, 04:40:11 at processTicksAndRejections (internal/process/task_queues.js:97:5)
24.2.2021, 04:40:11 (node:6150) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
24.2.2021, 04:40:11 [RademacherHomePilot] PUT error for path http://192.168.178.30/devices/1010018: ReferenceError: err is not defined
    at /home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherThermostatAccessory.js:90:9
    at /home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:122:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
24.2.2021, 04:40:11 (node:6150) UnhandledPromiseRejectionWarning: ReferenceError: err is not defined
24.2.2021, 04:40:11 at /home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherThermostatAccessory.js:90:9
24.2.2021, 04:40:11 at /home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:126:9
24.2.2021, 04:40:11 at runMicrotasks (<anonymous>)
24.2.2021, 04:40:11 at processTicksAndRejections (internal/process/task_queues.js:97:5)
24.2.2021, 04:40:11 (node:6150) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)

**Comment by bombadiltom** [comment]
Moinsen, fix ich heute im Laufe des Vormittags. Danke fürs Testen, habe mein einziges Thermostat nicht mehr angeschlossen, nachdem es bei leerer Batterie den Raum auf 40 Grad geheizt hatte...
