### ISSUE TITLE
Add Device 14236011

### ISSUE THREAD

**Issue by R3xRay** [bombadiltom/homebridge-rademacher-homepilot#88]
Can you include the device 14236011 in the index.js? I currently have to do this manually after each update. :)

It is the Rollotron Duofern 9800 pro

![image](https://user-images.githubusercontent.com/27278456/108967594-02cfdb00-7680-11eb-8943-2b6f2cbbdeb1.png)

**Comment by bombadiltom** [comment]
done, but, hey, this is open source, please create a pull request for such things in future
