### ISSUE TITLE
Teilweise funktioniert das schalten nicht

### ISSUE THREAD

**Issue by irstmon** [bombadiltom/homebridge-rademacher-homepilot#9]
Hi,

Ich habe das ganze ja schon ein paar Monate im Einsatz, in letzter Zeit fällt mir aber auf, dass es immer häufiger vorkommt, dass ich per Siri schalte, in Home auch sehe, dass geschaltet worden ist - aber der Aktor (und auch im Homepilot) tatsächlich nichts gemacht hat. Z.B. ein Licht das jetzt aus ist per Home anschalten, Home meldet ist angeschaltet - passiert ist nix. Schalte ich dann per Home nochmal aus und nochmal an macht er es auch tatsächlich. Neustart von Homepilot und Homebridge hat den Fehler bisher nicht behoben. Tritt auch leider nicht jedes mal auf, ist daher natürlich auch schlecht nachzuvollziehen. Was mir aber auf der Konsole von Homebridge aufgefallen ist: Es kommt beim ersten mal nach dem " Setting switch: true" ein "switch changed=false" und die nachfolgenden male tatsächlich ein "switch changed=true"

**Comment by bombadiltom** [comment]
Kommt denn beim Wechsel in den Raum in der Home App ein "Getting current state for [id]"?
Wenn das nicht passiert, hat das Plugin erst nach dem Schalten den korrekten Status (kann ja auch im Homepilot oder woanders geschaltet worden sein).

Welche Version nutzt du? Vom Plugin und welche iOS-Version?

Ich hatte das auch schonmal bemerkt, aber bisher nicht reproduzieren können. 
Ggf. ist das auch ein Bug in der Home-App oder HomeKit selbst...

**Comment by bombadiltom** [comment]
Sollte mit 0.1.0 behoben sein
