### ISSUE TITLE
Umweltsensor - not all sensors show up (missing wind and rain)

### ISSUE THREAD

**Issue by modellbobby** [bombadiltom/homebridge-rademacher-homepilot#91]
Dear developer, can you check please. using Homepilot 3 and Umweltsensor. I get the Lightsensor and Temp Sensor in Homebridge but not rain, wind, sun angle.

Can you check ?

**Comment by bombadiltom** [comment]
no need to check, I did not add the "Umweltsensor", someone else did.
And as I do not have a "Umweltsensor", I do not think I will add it in near future.

**Comment by modellbobby** [comment]
Could you help identify the developer who coded this feature ?

**Comment by modellbobby** [comment]
This is how I can see all the sensors 
http://homepilot.local/v4/devices?devtype=Sensor

**Comment by bombadiltom** [comment]
https://github.com/sg70

**Comment by modellbobby** [comment]
Hello Tom, can you guide me how to read the data from the rain sensor and send the data to homebridge as Leak Sensor (as there is no rain Sensor type there yet) I can develop it myself but need some advice how to get the data from the sensor under "rain_detected"

http://homepilot.local/v4/devices?devtype=Sensor

{"response":"get_meters","meters":[{"description":"Umweltsensor","deviceGroup":3,"did":14,"automations":[30,50,60,100,20,40],"readings":{"sun_detected":false,"sun_brightness":1000,"sun_direction":247.5,"sun_elevation":9,"wind_speed":0.0,"rain_detected":false,"temperature_primary":9.1},"timestamp":1614614382,"iconSetInverted":0,"iconSet":{"k":"iconset19"},"name":"Umweltsensor","statusValid":true,"deviceNumber":"32000064_S","uid":"69010a_S_1","visible":true}]}

**Comment by bombadiltom** [comment]
should be the same as in the sun sensor:
https://github.com/bombadiltom/homebridge-rademacher-homepilot/blob/7c4802c27792376561dd8251334dc131d7c62bd4/accessories/RademacherSunSensorAccessory.js#L40

**Comment by modellbobby** [comment]
Thank you , I ll try it and send a pull request

**Comment by modellbobby** [comment]
Hi Tom, can you help here please . How can I compile the code on my raspberry locally and use it in homebridge before sending a pull request ? 

Thank you / Danke

**Comment by bombadiltom** [comment]
use deploy.sh, maybe remove/comment out the line which removes the cachedAccessories, otherwise you'll lose the information in which room your devices are located

**Comment by bombadiltom** [comment]
pr merged and published as 0.8.0, thanks for that, any idea for wind sensor?

**Comment by modellbobby** [comment]
Netatmo is providing a HomeKit wind sensor. There should be then a device
type for this in HomeKit. I will check.

Tom Lorenz <notifications@github.com> schrieb am Di. 2. März 2021 um 09:23:

**Comment by modellbobby** [comment]
I think we can look at https://www.npmjs.com/package/homebridge-weather-plus
They have implemented Wind speed etc.

**Comment by sg70** [comment]
Hi @modellbobby / @bombadiltom,

there was a reason why I didn't implemented all possible values. The HomeKit API doesn't support those values.
Temperature (CurrentTemperature), light (CurrentAmbientLightLevel) and rain detection (LeakSensor) are support by HomeKit. 
Wind speed, sun elevation and sun  azimuth aren't support.

Modules for other device (such as weather plus) do implement workaround (e.g. OccupancyDetected) using a boolean like type and a threshold to turn the value to 1. Personally I don't like such workarounds as the nature of the value is not supported by HomeKit.

Pls find here the supported characteristics https://github.com/homebridge/HAP-NodeJS/blob/latest/src/lib/definitions/CharacteristicDefinitions.ts
Any idea which characteristic can be used for the missing values is welcome.
