### ISSUE TITLE
passiert hier noch etwas ?

### ISSUE THREAD

**Issue by modellbobby** [bombadiltom/homebridge-rademacher-homepilot#92]
Schau mal,

hilft dir diese Information weiter?

Die ID vom Umweltsensor findet man wie bei alle anderen Sensoren mit:
http://ip-vom-homepilot//deviceajax.do?sensors=1

Zu finden ist er unter "description":"Umweltsensor"

Dann lassen sich alle Werte vom Umweltsensor mit
http://ip-vom-homepilot/device…meter=id-vom-umweltsensor
auslesen.

Code
{ "response" : "get_meter_data", "status" : "ok", "data":[{"Lichtwert":"xxxxx lx"},{"Windgeschw.":"x m/s"},{"Temperatur":"xx.x °C"},{"Regen":"Nicht erkannt"},{"Sonnenhöhe":"xx°"},{"Sonnenrichtung":"x-x (xx°)"},{"Aktualisiert":"xx.xx.xx - xx:xx"}] }

Quelle: https://forum.smartapfel.de/forum/thread/593-rademacher-homepilot/?pageNo=2

_Originally posted by @Kohle81 in https://github.com/bombadiltom/homebridge-rademacher-homepilot/issues/5#issuecomment-430591859_

**Comment by bombadiltom** [comment]
duplicate of #91
