### ISSUE TITLE
Switches activated via scene can’t be controlled 

### ISSUE THREAD

**Issue by sebbi315** [bombadiltom/homebridge-rademacher-homepilot#98]
Hello Tom,

first of all THANK YOU, for this gerade plug-in.
Until the last update, don’t know whether the update of homebridge or your plugin caused my current issue, it worked perfectly. 

I‘m using the Homepilot to control my switches etc. in dependence to the values of the Umweltsensor via scenes. Since a couple of days, the homebridge can’t switch off the switches, switched on via Homepilot scenes. 
Do you have any idea? 

BR

**Comment by sebbi315** [comment]
I’ve to add, that it works right after a restart of the homebridge, but after a couple of hours it doesn’t work anymore. I’m using homebridge on my Synology.

**Comment by bombadiltom** [comment]
please provide some logs

**Comment by sebbi315** [comment]
For whatever reasons, my switches do not create log input in the logs... Just e.g. the blinds do create log input (cf. picture) 
![E9D64238-F4FB-4319-9275-C1967EE1BC4D](https://user-images.githubusercontent.com/80207641/111071518-d2d56400-84d6-11eb-84c9-c6cfea200930.png)

**Comment by sebbi315** [comment]
For whatever reasons, my switches do not create log input in the logs... Just e.g. the blinds do create log input (cf. picture)
![Uploading CC383D9F-CF79-46E9-B7F0-C9AC3B633E94.jpeg…]()

**Comment by sebbi315** [comment]
For whatever reasons, my switches do not create log input in the logs... Just e.g. the blinds do create log input (cf. picture)
![5E947D3D-ECD6-4AC2-BE47-0207B6AFFAD7](https://user-images.githubusercontent.com/80207641/111071598-33fd3780-84d7-11eb-9786-1b61c4017174.jpeg)

**Comment by bombadiltom** [comment]
please set debug to true and provide text files not screenshots

**Comment by bombadiltom** [comment]
no reaction
